/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Qualcomm Titan 680 (IFE) pixel path register definitions
 *
 * Generated from the SoC register description. Every pixel path CLC
 * module shares a common header:
 *
 *   +0x000  HW_VERSION
 *   +0x004  HW_STATUS
 *   +0x060  MODULE_CFG      bit 0 is the module enable
 *   +0x1f8  TEST_BUS_CTRL
 *   +0x1fc  SPARE
 *
 * Module registers are therefore VFE_PP_BASE + <module base> + <offset>.
 */

#ifndef __CAMSS_VFE_680_PP_REGS_H__
#define __CAMSS_VFE_680_PP_REGS_H__

/* Pixel path block base within the IFE register space */
#define VFE_PP_BASE					0x3900

#define	VFE_PP_MODULE_CFG_EN				BIT(0)

/* DEMUX  (base 0x0000, absolute 0x3900) */
#define VFE_PP_CLC_DEMUX_HW_VERSION				0x3900
#define VFE_PP_CLC_DEMUX_HW_STATUS				0x3904
#define VFE_PP_CLC_DEMUX_MODULE_CFG				0x3960
#define VFE_PP_CLC_DEMUX_DEMUX_EVEN_LINE_CFG			0x3968
#define VFE_PP_CLC_DEMUX_DEMUX_ODD_LINE_CFG			0x396c
#define VFE_PP_CLC_DEMUX_TEST_BUS_CTRL				0x3af8
#define VFE_PP_CLC_DEMUX_SPARE					0x3afc

/* CHANNEL_GAIN  (base 0x0200, absolute 0x3b00) */
#define VFE_PP_CLC_CHANNEL_GAIN_HW_VERSION			0x3b00
#define VFE_PP_CLC_CHANNEL_GAIN_HW_STATUS			0x3b04
#define VFE_PP_CLC_CHANNEL_GAIN_MODULE_CFG			0x3b60
#define VFE_PP_CLC_CHANNEL_GAIN_DEMUX_CFG_0			0x3b68
#define VFE_PP_CLC_CHANNEL_GAIN_DEMUX_CFG_1			0x3b6c
#define VFE_PP_CLC_CHANNEL_GAIN_GAIN_CFG_0			0x3b70
#define VFE_PP_CLC_CHANNEL_GAIN_GAIN_CFG_1			0x3b74
#define VFE_PP_CLC_CHANNEL_GAIN_CH0_CFG_IN_EVEN			0x3b78
#define VFE_PP_CLC_CHANNEL_GAIN_CH0_CFG_IN_ODD			0x3b7c
#define VFE_PP_CLC_CHANNEL_GAIN_CH1_CFG_IN			0x3b80
#define VFE_PP_CLC_CHANNEL_GAIN_CH2_CFG_IN			0x3b84
#define VFE_PP_CLC_CHANNEL_GAIN_CH0_CFG_OUT_EVEN		0x3b88
#define VFE_PP_CLC_CHANNEL_GAIN_CH0_CFG_OUT_ODD			0x3b8c
#define VFE_PP_CLC_CHANNEL_GAIN_CH1_CFG_OUT			0x3b90
#define VFE_PP_CLC_CHANNEL_GAIN_CH2_CFG_OUT			0x3b94
#define VFE_PP_CLC_CHANNEL_GAIN_TEST_BUS_CTRL			0x3cf8
#define VFE_PP_CLC_CHANNEL_GAIN_SPARE				0x3cfc

/* BPC_PDPC  (base 0x0400, absolute 0x3d00) */
#define VFE_PP_CLC_BPC_PDPC_HW_VERSION				0x3d00
#define VFE_PP_CLC_BPC_PDPC_HW_STATUS				0x3d04
#define VFE_PP_CLC_BPC_PDPC_DMI_CFG				0x3d08
#define VFE_PP_CLC_BPC_PDPC_DMI_LUT_CFG				0x3d0c
#define VFE_PP_CLC_BPC_PDPC_DMI_DATA				0x3d10
#define VFE_PP_CLC_BPC_PDPC_DMI_CMD				0x3d50
#define VFE_PP_CLC_BPC_PDPC_DMI_STATUS				0x3d54
#define VFE_PP_CLC_BPC_PDPC_DMI_LUT_BANK_CFG			0x3d58
#define VFE_PP_CLC_BPC_PDPC_MODULE_LUT_BANK_CFG			0x3d5c
#define VFE_PP_CLC_BPC_PDPC_MODULE_CFG				0x3d60
#define VFE_PP_CLC_BPC_PDPC_PDPC_BLACK_LEVEL			0x3d68
#define VFE_PP_CLC_BPC_PDPC_BAD_PIXEL_THRESHOLDS		0x3d70
#define VFE_PP_CLC_BPC_PDPC_PDAF_RG_WB_GAIN			0x3d78
#define VFE_PP_CLC_BPC_PDPC_PDAF_BG_WB_GAIN			0x3d7c
#define VFE_PP_CLC_BPC_PDPC_PDAF_GR_WB_GAIN			0x3d80
#define VFE_PP_CLC_BPC_PDPC_PDAF_GB_WB_GAIN			0x3d84
#define VFE_PP_CLC_BPC_PDPC_PDAF_LOC_OFFSET_CFG			0x3d88
#define VFE_PP_CLC_BPC_PDPC_PDAF_LOC_END_CFG			0x3d8c
#define VFE_PP_CLC_BPC_PDPC_PDAF_TAB_OFFSET_CFG			0x3db4
#define VFE_PP_CLC_BPC_PDPC_DD_THRESHOLD_RATIO			0x3db8
#define VFE_PP_CLC_BPC_PDPC_BAD_PIXEL_DET_CFG			0x3dd4
#define VFE_PP_CLC_BPC_PDPC_BAD_PIXEL_DET_OFFSET		0x3dd8
#define VFE_PP_CLC_BPC_PDPC_TEST_BUS_CTRL			0x3ef8
#define VFE_PP_CLC_BPC_PDPC_SPARE				0x3efc
/* BPC_PDPC: 15 LUT/DMI entries at 0x3d14..0x3d4c, index with a stride of 4 */

/* BINCORRECT  (base 0x0600, absolute 0x3f00) */
#define VFE_PP_CLC_BINCORRECT_HW_VERSION			0x3f00
#define VFE_PP_CLC_BINCORRECT_HW_STATUS				0x3f04
#define VFE_PP_CLC_BINCORRECT_MODULE_CFG			0x3f60
#define VFE_PP_CLC_BINCORRECT_BIN_CORR_0_CFG			0x3f64
#define VFE_PP_CLC_BINCORRECT_BIN_CORR_1_CFG			0x3f68
#define VFE_PP_CLC_BINCORRECT_TEST_BUS_CTRL			0x40f8
#define VFE_PP_CLC_BINCORRECT_SPARE				0x40fc

/* COMPDECOMP  (base 0x0800, absolute 0x4100) */
#define VFE_PP_CLC_COMPDECOMP_HW_VERSION			0x4100
#define VFE_PP_CLC_COMPDECOMP_HW_STATUS				0x4104
#define VFE_PP_CLC_COMPDECOMP_MODULE_CFG			0x4160
#define VFE_PP_CLC_COMPDECOMP_KNEE_CFG_0			0x4168
#define VFE_PP_CLC_COMPDECOMP_KNEE_CFG_1			0x416c
#define VFE_PP_CLC_COMPDECOMP_KNEE_CFG_2			0x4170
#define VFE_PP_CLC_COMPDECOMP_KNEE_CFG_3			0x4174
#define VFE_PP_CLC_COMPDECOMP_KNEE_CFG_4			0x4178
#define VFE_PP_CLC_COMPDECOMP_KNEE_CFG_5			0x417c
#define VFE_PP_CLC_COMPDECOMP_KNEE_CFG_6			0x4180
#define VFE_PP_CLC_COMPDECOMP_KNEE_CFG_7			0x4184
#define VFE_PP_CLC_COMPDECOMP_KNEE_CFG_8			0x4188
#define VFE_PP_CLC_COMPDECOMP_KNEE_CFG_9			0x418c
#define VFE_PP_CLC_COMPDECOMP_KNEE_CFG_10			0x4190
#define VFE_PP_CLC_COMPDECOMP_KNEE_CFG_11			0x4194
#define VFE_PP_CLC_COMPDECOMP_KNEE_CFG_12			0x4198
#define VFE_PP_CLC_COMPDECOMP_KNEE_CFG_13			0x419c
#define VFE_PP_CLC_COMPDECOMP_KNEE_CFG_14			0x41a0
#define VFE_PP_CLC_COMPDECOMP_BASE_CFG_0			0x41b4
#define VFE_PP_CLC_COMPDECOMP_BASE_CFG_1			0x41b8
#define VFE_PP_CLC_COMPDECOMP_BASE_CFG_2			0x41bc
#define VFE_PP_CLC_COMPDECOMP_BASE_CFG_3			0x41c0
#define VFE_PP_CLC_COMPDECOMP_BASE_CFG_4			0x41c4
#define VFE_PP_CLC_COMPDECOMP_BASE_CFG_5			0x41c8
#define VFE_PP_CLC_COMPDECOMP_BASE_CFG_6			0x41cc
#define VFE_PP_CLC_COMPDECOMP_BASE_CFG_7			0x41d0
#define VFE_PP_CLC_COMPDECOMP_BASE_CFG_8			0x41d4
#define VFE_PP_CLC_COMPDECOMP_BASE_CFG_9			0x41d8
#define VFE_PP_CLC_COMPDECOMP_BASE_CFG_10			0x41dc
#define VFE_PP_CLC_COMPDECOMP_BASE_CFG_11			0x41e0
#define VFE_PP_CLC_COMPDECOMP_BASE_CFG_12			0x41e4
#define VFE_PP_CLC_COMPDECOMP_BASE_CFG_13			0x41e8
#define VFE_PP_CLC_COMPDECOMP_BASE_CFG_14			0x41ec
#define VFE_PP_CLC_COMPDECOMP_BASE_CFG_15			0x41f0
#define VFE_PP_CLC_COMPDECOMP_TEST_BUS_CTRL			0x42f8
#define VFE_PP_CLC_COMPDECOMP_SPARE				0x42fc
/* COMPDECOMP: 16 LUT/DMI entries at 0x4200..0x4250, index with a stride of 4 */

/* LSC  (base 0x0a00, absolute 0x4300) */
#define VFE_PP_CLC_LSC_HW_VERSION				0x4300
#define VFE_PP_CLC_LSC_HW_STATUS				0x4304
#define VFE_PP_CLC_LSC_DMI_CFG					0x4308
#define VFE_PP_CLC_LSC_DMI_LUT_CFG				0x430c
#define VFE_PP_CLC_LSC_DMI_DATA					0x4310
#define VFE_PP_CLC_LSC_DMI_CMD					0x4350
#define VFE_PP_CLC_LSC_DMI_STATUS				0x4354
#define VFE_PP_CLC_LSC_DMI_LUT_BANK_CFG				0x4358
#define VFE_PP_CLC_LSC_MODULE_LUT_BANK_CFG			0x435c
#define VFE_PP_CLC_LSC_MODULE_CFG				0x4360
#define VFE_PP_CLC_LSC_LSC_0_CFG				0x4368
#define VFE_PP_CLC_LSC_LSC_1_CFG				0x436c
#define VFE_PP_CLC_LSC_LSC_2_CFG				0x4370
#define VFE_PP_CLC_LSC_LSC_3_CFG				0x4374
#define VFE_PP_CLC_LSC_LSC_4_CFG				0x4378
#define VFE_PP_CLC_LSC_LSC_5_CFG				0x437c
#define VFE_PP_CLC_LSC_LSC_6_CFG				0x4380
#define VFE_PP_CLC_LSC_LSC_7_CFG				0x4384
#define VFE_PP_CLC_LSC_LSC_8_CFG				0x4388
#define VFE_PP_CLC_LSC_LSC_9_CFG				0x438c
#define VFE_PP_CLC_LSC_LSC_10_CFG				0x4390
#define VFE_PP_CLC_LSC_LSC_11_CFG				0x4394
#define VFE_PP_CLC_LSC_LSC_12_CFG				0x4398
#define VFE_PP_CLC_LSC_TEST_BUS_CTRL				0x44f8
#define VFE_PP_CLC_LSC_SPARE					0x44fc
/* LSC: 15 LUT/DMI entries at 0x4314..0x434c, index with a stride of 4 */

/* WB_GAIN  (base 0x0c00, absolute 0x4500) */
#define VFE_PP_CLC_WB_GAIN_HW_VERSION				0x4500
#define VFE_PP_CLC_WB_GAIN_HW_STATUS				0x4504
#define VFE_PP_CLC_WB_GAIN_MODULE_CFG				0x4560
#define VFE_PP_CLC_WB_GAIN_WB_CFG_0				0x4568
#define VFE_PP_CLC_WB_GAIN_WB_CFG_1				0x456c
#define VFE_PP_CLC_WB_GAIN_WB_CFG_2				0x4570
#define VFE_PP_CLC_WB_GAIN_WB_OFFSET_CFG_0			0x4574
#define VFE_PP_CLC_WB_GAIN_WB_OFFSET_CFG_1			0x4578
#define VFE_PP_CLC_WB_GAIN_WB_OFFSET_CFG_2			0x457c
#define VFE_PP_CLC_WB_GAIN_WB_OFFSET_CFG_3			0x4580
#define VFE_PP_CLC_WB_GAIN_WB_OFFSET_CFG_4			0x4584
#define VFE_PP_CLC_WB_GAIN_WB_OFFSET_CFG_5			0x4588
#define VFE_PP_CLC_WB_GAIN_WB_RECOV_CFG_0			0x458c
#define VFE_PP_CLC_WB_GAIN_WB_RECOV_CFG_1			0x4590
#define VFE_PP_CLC_WB_GAIN_WB_RECOV_CFG_2			0x4594
#define VFE_PP_CLC_WB_GAIN_TEST_BUS_CTRL			0x46f8
#define VFE_PP_CLC_WB_GAIN_SPARE				0x46fc

/* GIC  (base 0x0e00, absolute 0x4700) */
#define VFE_PP_CLC_GIC_HW_VERSION				0x4700
#define VFE_PP_CLC_GIC_HW_STATUS				0x4704
#define VFE_PP_CLC_GIC_DMI_CFG					0x4708
#define VFE_PP_CLC_GIC_DMI_LUT_CFG				0x470c
#define VFE_PP_CLC_GIC_DMI_DATA					0x4710
#define VFE_PP_CLC_GIC_DMI_CMD					0x4750
#define VFE_PP_CLC_GIC_DMI_STATUS				0x4754
#define VFE_PP_CLC_GIC_DMI_LUT_BANK_CFG				0x4758
#define VFE_PP_CLC_GIC_MODULE_LUT_BANK_CFG			0x475c
#define VFE_PP_CLC_GIC_MODULE_CFG				0x4760
#define VFE_PP_CLC_GIC_GIC_FILTER_CFG				0x4770
#define VFE_PP_CLC_GIC_THIN_LINE_NOISE_OFFSET			0x4774
#define VFE_PP_CLC_GIC_TEST_BUS_CTRL				0x48f8
#define VFE_PP_CLC_GIC_SPARE					0x48fc
/* GIC: 15 LUT/DMI entries at 0x4714..0x474c, index with a stride of 4 */

/* BPC_ABF  (base 0x1000, absolute 0x4900) */
#define VFE_PP_CLC_BPC_ABF_HW_VERSION				0x4900
#define VFE_PP_CLC_BPC_ABF_HW_STATUS				0x4904
#define VFE_PP_CLC_BPC_ABF_DMI_CFG				0x4908
#define VFE_PP_CLC_BPC_ABF_DMI_LUT_CFG				0x490c
#define VFE_PP_CLC_BPC_ABF_DMI_DATA				0x4910
#define VFE_PP_CLC_BPC_ABF_DMI_CMD				0x4950
#define VFE_PP_CLC_BPC_ABF_DMI_STATUS				0x4954
#define VFE_PP_CLC_BPC_ABF_DMI_LUT_BANK_CFG			0x4958
#define VFE_PP_CLC_BPC_ABF_MODULE_LUT_BANK_CFG			0x495c
#define VFE_PP_CLC_BPC_ABF_MODULE_CFG				0x4960
#define VFE_PP_CLC_BPC_ABF_BPC_CFG				0x4968
#define VFE_PP_CLC_BPC_ABF_ABF_CFG				0x496c
#define VFE_PP_CLC_BPC_ABF_BPC_DETECT_CFG0			0x4980
#define VFE_PP_CLC_BPC_ABF_BPC_DETECT_CFG1			0x4984
#define VFE_PP_CLC_BPC_ABF_BPC_DETECT_CFG2			0x4988
#define VFE_PP_CLC_BPC_ABF_BPC_RECOVERY_CFG			0x498c
#define VFE_PP_CLC_BPC_ABF_ABF_SINGLE_BPC_CFG0			0x49a0
#define VFE_PP_CLC_BPC_ABF_ABF_SINGLE_BPC_CFG1			0x49a4
#define VFE_PP_CLC_BPC_ABF_ABF_SINGLE_BPC_CFG2			0x49a8
#define VFE_PP_CLC_BPC_ABF_ABF_FILTER_CFG0			0x49ac
#define VFE_PP_CLC_BPC_ABF_ABF_FILTER_CFG1			0x49b0
#define VFE_PP_CLC_BPC_ABF_NOISE_PRSV_ANCHOR_CFG		0x49b4
#define VFE_PP_CLC_BPC_ABF_NOISE_PRSV_RB_CFG			0x49b8
#define VFE_PP_CLC_BPC_ABF_NOISE_PRSV_GRGB_CFG			0x49bc
#define VFE_PP_CLC_BPC_ABF_RNR_ANCHOR_CFG_0			0x49c8
#define VFE_PP_CLC_BPC_ABF_RNR_ANCHOR_CFG_1			0x49cc
#define VFE_PP_CLC_BPC_ABF_NOISE_RNR_BASE_CFG			0x49d0
#define VFE_PP_CLC_BPC_ABF_THRESH_RNR_BASE_CFG			0x49d4
#define VFE_PP_CLC_BPC_ABF_NOISE_RNR_SLOPE_CFG			0x49d8
#define VFE_PP_CLC_BPC_ABF_THRESH_RNR_SLOPE_CFG			0x49dc
#define VFE_PP_CLC_BPC_ABF_RNR_SHIFT_CFG			0x49e0
#define VFE_PP_CLC_BPC_ABF_RNR_INIT_OFFSET_CFG			0x49e4
#define VFE_PP_CLC_BPC_ABF_RNR_SQUARE_CFG			0x49e8
#define VFE_PP_CLC_BPC_ABF_DEBUG_0				0x4af4
#define VFE_PP_CLC_BPC_ABF_TEST_BUS_CTRL			0x4af8
#define VFE_PP_CLC_BPC_ABF_SPARE				0x4afc
/* BPC_ABF: 15 LUT/DMI entries at 0x4914..0x494c, index with a stride of 4 */

/* BLS  (base 0x1200, absolute 0x4b00) */
#define VFE_PP_CLC_BLS_HW_VERSION				0x4b00
#define VFE_PP_CLC_BLS_HW_STATUS				0x4b04
#define VFE_PP_CLC_BLS_MODULE_CFG				0x4b60
#define VFE_PP_CLC_BLS_CFG_0					0x4b68
#define VFE_PP_CLC_BLS_CFG_1					0x4b6c
#define VFE_PP_CLC_BLS_THRESHOLD_CFG_0				0x4b70
#define VFE_PP_CLC_BLS_THRESHOLD_CFG_1				0x4b74
#define VFE_PP_CLC_BLS_THRESHOLD_CFG_2				0x4b78
#define VFE_PP_CLC_BLS_THRESHOLD_CFG_3				0x4b7c
#define VFE_PP_CLC_BLS_TEST_BUS_CTRL				0x4cf8
#define VFE_PP_CLC_BLS_SPARE					0x4cfc

/* BAYER_GTM  (base 0x1400, absolute 0x4d00) */
#define VFE_PP_CLC_BAYER_GTM_HW_VERSION				0x4d00
#define VFE_PP_CLC_BAYER_GTM_HW_STATUS				0x4d04
#define VFE_PP_CLC_BAYER_GTM_DMI_CFG				0x4d08
#define VFE_PP_CLC_BAYER_GTM_DMI_LUT_CFG			0x4d0c
#define VFE_PP_CLC_BAYER_GTM_DMI_DATA				0x4d10
#define VFE_PP_CLC_BAYER_GTM_DMI_CMD				0x4d50
#define VFE_PP_CLC_BAYER_GTM_DMI_STATUS				0x4d54
#define VFE_PP_CLC_BAYER_GTM_DMI_LUT_BANK_CFG			0x4d58
#define VFE_PP_CLC_BAYER_GTM_MODULE_LUT_BANK_CFG		0x4d5c
#define VFE_PP_CLC_BAYER_GTM_MODULE_CFG				0x4d60
#define VFE_PP_CLC_BAYER_GTM_C1_COEFF				0x4d64
#define VFE_PP_CLC_BAYER_GTM_C2_COEFF				0x4d68
#define VFE_PP_CLC_BAYER_GTM_C3_COEFF				0x4d6c
#define VFE_PP_CLC_BAYER_GTM_C4_COEFF				0x4d70
#define VFE_PP_CLC_BAYER_GTM_TEST_BUS_CTRL			0x51f8
#define VFE_PP_CLC_BAYER_GTM_SPARE				0x51fc
/* BAYER_GTM: 271 LUT/DMI entries at 0x4d14..0x5170, index with a stride of 4 */

/* BAYER_LTM  (base 0x1900, absolute 0x5200) */
#define VFE_PP_CLC_BAYER_LTM_HW_VERSION				0x5200
#define VFE_PP_CLC_BAYER_LTM_HW_STATUS				0x5204
#define VFE_PP_CLC_BAYER_LTM_DMI_CFG				0x5208
#define VFE_PP_CLC_BAYER_LTM_DMI_LUT_CFG			0x520c
#define VFE_PP_CLC_BAYER_LTM_DMI_DATA				0x5210
#define VFE_PP_CLC_BAYER_LTM_DMI_CMD				0x5250
#define VFE_PP_CLC_BAYER_LTM_DMI_STATUS				0x5254
#define VFE_PP_CLC_BAYER_LTM_DMI_LUT_BANK_CFG			0x5258
#define VFE_PP_CLC_BAYER_LTM_MODULE_LUT_BANK_CFG		0x525c
#define VFE_PP_CLC_BAYER_LTM_MODULE_CFG				0x5260
#define VFE_PP_CLC_BAYER_LTM_DC_CFG_0				0x5268
#define VFE_PP_CLC_BAYER_LTM_DC_CFG_1				0x526c
#define VFE_PP_CLC_BAYER_LTM_DC_CFG_2				0x5270
#define VFE_PP_CLC_BAYER_LTM_RGB2Y_CFG				0x5274
#define VFE_PP_CLC_BAYER_LTM_IP_0_CFG				0x5278
#define VFE_PP_CLC_BAYER_LTM_IP_1_CFG				0x527c
#define VFE_PP_CLC_BAYER_LTM_IP_2_CFG				0x5280
#define VFE_PP_CLC_BAYER_LTM_IP_3_CFG				0x5284
#define VFE_PP_CLC_BAYER_LTM_IP_4_CFG				0x5288
#define VFE_PP_CLC_BAYER_LTM_IP_5_CFG				0x528c
#define VFE_PP_CLC_BAYER_LTM_IP_6_CFG				0x5290
#define VFE_PP_CLC_BAYER_LTM_IP_7_CFG				0x5294
#define VFE_PP_CLC_BAYER_LTM_MASK_2_CFG				0x52a0
#define VFE_PP_CLC_BAYER_LTM_MASK_3_CFG				0x52a4
#define VFE_PP_CLC_BAYER_LTM_DOWNSCALE_MN_Y_CFG			0x52b0
#define VFE_PP_CLC_BAYER_LTM_DOWNSCALE_MN_Y_IMAGE_SIZE_CFG	0x52b4
#define VFE_PP_CLC_BAYER_LTM_DOWNSCALE_MN_Y_H_CFG		0x52b8
#define VFE_PP_CLC_BAYER_LTM_DOWNSCALE_MN_Y_H_PHASE_CFG		0x52bc
#define VFE_PP_CLC_BAYER_LTM_DOWNSCALE_MN_Y_V_CFG		0x52c0
#define VFE_PP_CLC_BAYER_LTM_DOWNSCALE_MN_Y_V_PHASE_CFG		0x52c4
#define VFE_PP_CLC_BAYER_LTM_TEST_BUS_CTRL			0x53f8
#define VFE_PP_CLC_BAYER_LTM_SPARE				0x53fc
/* BAYER_LTM: 15 LUT/DMI entries at 0x5214..0x524c, index with a stride of 4 */

/* LCAC  (base 0x1b00, absolute 0x5400) */
#define VFE_PP_CLC_LCAC_HW_VERSION				0x5400
#define VFE_PP_CLC_LCAC_HW_STATUS				0x5404
#define VFE_PP_CLC_LCAC_DMI_CFG					0x5408
#define VFE_PP_CLC_LCAC_DMI_LUT_CFG				0x540c
#define VFE_PP_CLC_LCAC_DMI_DATA				0x5410
#define VFE_PP_CLC_LCAC_DMI_CMD					0x5450
#define VFE_PP_CLC_LCAC_DMI_STATUS				0x5454
#define VFE_PP_CLC_LCAC_DMI_LUT_BANK_CFG			0x5458
#define VFE_PP_CLC_LCAC_MODULE_LUT_BANK_CFG			0x545c
#define VFE_PP_CLC_LCAC_MODULE_CFG				0x5460
#define VFE_PP_CLC_LCAC_INPUT_STRIP_WIDTH_MINUS_1		0x5464
#define VFE_PP_CLC_LCAC_INPUT_STRIP_HEIGHT_MINUS_1		0x5468
#define VFE_PP_CLC_LCAC_START_STEP_X_MSB			0x546c
#define VFE_PP_CLC_LCAC_START_STEP_X_LSB			0x5470
#define VFE_PP_CLC_LCAC_START_STEP_Y_MSB			0x5474
#define VFE_PP_CLC_LCAC_START_STEP_Y_LSB			0x5478
#define VFE_PP_CLC_LCAC_START_R2_MSB				0x547c
#define VFE_PP_CLC_LCAC_START_R2_LSB				0x5480
#define VFE_PP_CLC_LCAC_STEP_X_MSB				0x5484
#define VFE_PP_CLC_LCAC_STEP_X_LSB				0x5488
#define VFE_PP_CLC_LCAC_STEP_Y_MSB				0x548c
#define VFE_PP_CLC_LCAC_STEP_Y_LSB				0x5490
#define VFE_PP_CLC_LCAC_OPTICAL_CENTER_X			0x5494
#define VFE_PP_CLC_LCAC_OPTICAL_CENTER_Y			0x5498
#define VFE_PP_CLC_LCAC_INTERPOLATION_TYPE			0x54a4
#define VFE_PP_CLC_LCAC_PADDING_TYPE				0x54a8
#define VFE_PP_CLC_LCAC_CROP_ENABLE				0x54ac
#define VFE_PP_CLC_LCAC_TEST_BUS_CTRL				0x55f8
#define VFE_PP_CLC_LCAC_SPARE					0x55fc
/* LCAC: 17 LUT/DMI entries at 0x5414..0x54a0, index with a stride of 4 */

/* DEMOSAIC  (base 0x1d00, absolute 0x5600) */
#define VFE_PP_CLC_DEMOSAIC_HW_VERSION				0x5600
#define VFE_PP_CLC_DEMOSAIC_HW_STATUS				0x5604
#define VFE_PP_CLC_DEMOSAIC_MODULE_CFG				0x5660
#define VFE_PP_CLC_DEMOSAIC_INTERP_COEFF_CFG_0			0x5668
#define VFE_PP_CLC_DEMOSAIC_INTERP_COEFF_CFG_1			0x566c
#define VFE_PP_CLC_DEMOSAIC_INTERP_CLASSIFIER_CFG_0		0x5670
#define VFE_PP_CLC_DEMOSAIC_INTERP_CLASSIFIER_CFG_1		0x5674
#define VFE_PP_CLC_DEMOSAIC_DEBUG_0				0x57f4
#define VFE_PP_CLC_DEMOSAIC_TEST_BUS_CTRL			0x57f8
#define VFE_PP_CLC_DEMOSAIC_SPARE				0x57fc

/* COLOR_CORRECT  (base 0x1f00, absolute 0x5800) */
#define VFE_PP_CLC_COLOR_CORRECT_HW_VERSION			0x5800
#define VFE_PP_CLC_COLOR_CORRECT_HW_STATUS			0x5804
#define VFE_PP_CLC_COLOR_CORRECT_MODULE_CFG			0x5860
#define VFE_PP_CLC_COLOR_CORRECT_COLOR_CORRECT_COEFF_A_CFG_0	0x5868
#define VFE_PP_CLC_COLOR_CORRECT_COLOR_CORRECT_COEFF_A_CFG_1	0x586c
#define VFE_PP_CLC_COLOR_CORRECT_COLOR_CORRECT_COEFF_B_CFG_0	0x5870
#define VFE_PP_CLC_COLOR_CORRECT_COLOR_CORRECT_COEFF_B_CFG_1	0x5874
#define VFE_PP_CLC_COLOR_CORRECT_COLOR_CORRECT_COEFF_C_CFG_0	0x5878
#define VFE_PP_CLC_COLOR_CORRECT_COLOR_CORRECT_COEFF_C_CFG_1	0x587c
#define VFE_PP_CLC_COLOR_CORRECT_COLOR_CORRECT_OFFSET_K_CFG_0	0x5880
#define VFE_PP_CLC_COLOR_CORRECT_COLOR_CORRECT_OFFSET_K_CFG_1	0x5884
#define VFE_PP_CLC_COLOR_CORRECT_COLOR_CORRECT_OFFSET_K_CFG_2	0x5888
#define VFE_PP_CLC_COLOR_CORRECT_COLOR_CORRECT_SHIFT_M_CFG	0x588c
#define VFE_PP_CLC_COLOR_CORRECT_TEST_BUS_CTRL			0x59f8
#define VFE_PP_CLC_COLOR_CORRECT_SPARE				0x59fc

/* GTM  (base 0x2100, absolute 0x5a00) */
#define VFE_PP_CLC_GTM_HW_VERSION				0x5a00
#define VFE_PP_CLC_GTM_HW_STATUS				0x5a04
#define VFE_PP_CLC_GTM_DMI_CFG					0x5a08
#define VFE_PP_CLC_GTM_DMI_LUT_CFG				0x5a0c
#define VFE_PP_CLC_GTM_DMI_DATA					0x5a10
#define VFE_PP_CLC_GTM_DMI_CMD					0x5a50
#define VFE_PP_CLC_GTM_DMI_STATUS				0x5a54
#define VFE_PP_CLC_GTM_DMI_LUT_BANK_CFG				0x5a58
#define VFE_PP_CLC_GTM_MODULE_LUT_BANK_CFG			0x5a5c
#define VFE_PP_CLC_GTM_MODULE_CFG				0x5a60
#define VFE_PP_CLC_GTM_C1_COEFF					0x5a64
#define VFE_PP_CLC_GTM_C2_COEFF					0x5a68
#define VFE_PP_CLC_GTM_C3_COEFF					0x5a6c
#define VFE_PP_CLC_GTM_C4_COEFF					0x5a70
#define VFE_PP_CLC_GTM_TEST_BUS_CTRL				0x5ef8
#define VFE_PP_CLC_GTM_SPARE					0x5efc
/* GTM: 271 LUT/DMI entries at 0x5a14..0x5e70, index with a stride of 4 */

/* GLUT  (base 0x2600, absolute 0x5f00) */
#define VFE_PP_CLC_GLUT_HW_VERSION				0x5f00
#define VFE_PP_CLC_GLUT_HW_STATUS				0x5f04
#define VFE_PP_CLC_GLUT_DMI_CFG					0x5f08
#define VFE_PP_CLC_GLUT_DMI_LUT_CFG				0x5f0c
#define VFE_PP_CLC_GLUT_DMI_DATA				0x5f10
#define VFE_PP_CLC_GLUT_DMI_CMD					0x5f50
#define VFE_PP_CLC_GLUT_DMI_STATUS				0x5f54
#define VFE_PP_CLC_GLUT_DMI_LUT_BANK_CFG			0x5f58
#define VFE_PP_CLC_GLUT_MODULE_LUT_BANK_CFG			0x5f5c
#define VFE_PP_CLC_GLUT_MODULE_CFG				0x5f60
#define VFE_PP_CLC_GLUT_TEST_BUS_CTRL				0x60f8
#define VFE_PP_CLC_GLUT_SPARE					0x60fc
/* GLUT: 15 LUT/DMI entries at 0x5f14..0x5f4c, index with a stride of 4 */

/* COLOR_XFORM  (base 0x2800, absolute 0x6100) */
#define VFE_PP_CLC_COLOR_XFORM_HW_VERSION			0x6100
#define VFE_PP_CLC_COLOR_XFORM_HW_STATUS			0x6104
#define VFE_PP_CLC_COLOR_XFORM_MODULE_CFG			0x6160
#define VFE_PP_CLC_COLOR_XFORM_COLOR_XFORM_CH0_COEFF_CFG_0	0x6168
#define VFE_PP_CLC_COLOR_XFORM_COLOR_XFORM_CH0_COEFF_CFG_1	0x616c
#define VFE_PP_CLC_COLOR_XFORM_COLOR_XFORM_CH0_ADDOFFSET_CFG	0x6170
#define VFE_PP_CLC_COLOR_XFORM_COLOR_XFORM_CH0_SUBOFFSET_CFG	0x6174
#define VFE_PP_CLC_COLOR_XFORM_COLOR_XFORM_CH0_CLAMP0_CFG	0x6178
#define VFE_PP_CLC_COLOR_XFORM_COLOR_XFORM_CH0_CLAMP1_CFG	0x617c
#define VFE_PP_CLC_COLOR_XFORM_COLOR_XFORM_CH1_COEFF_CFG_0	0x6180
#define VFE_PP_CLC_COLOR_XFORM_COLOR_XFORM_CH1_COEFF_CFG_1	0x6184
#define VFE_PP_CLC_COLOR_XFORM_COLOR_XFORM_CH1_ADDOFFSET_CFG	0x6188
#define VFE_PP_CLC_COLOR_XFORM_COLOR_XFORM_CH1_SUBOFFSET_CFG	0x618c
#define VFE_PP_CLC_COLOR_XFORM_COLOR_XFORM_CH1_CLAMP0_CFG	0x6190
#define VFE_PP_CLC_COLOR_XFORM_COLOR_XFORM_CH1_CLAMP1_CFG	0x6194
#define VFE_PP_CLC_COLOR_XFORM_COLOR_XFORM_CH2_COEFF_CFG_0	0x6198
#define VFE_PP_CLC_COLOR_XFORM_COLOR_XFORM_CH2_COEFF_CFG_1	0x619c
#define VFE_PP_CLC_COLOR_XFORM_COLOR_XFORM_CH2_ADDOFFSET_CFG	0x61a0
#define VFE_PP_CLC_COLOR_XFORM_COLOR_XFORM_CH2_SUBOFFSET_CFG	0x61a4
#define VFE_PP_CLC_COLOR_XFORM_COLOR_XFORM_CH2_CLAMP0_CFG	0x61a8
#define VFE_PP_CLC_COLOR_XFORM_COLOR_XFORM_CH2_CLAMP1_CFG	0x61ac
#define VFE_PP_CLC_COLOR_XFORM_TEST_BUS_CTRL			0x62f8
#define VFE_PP_CLC_COLOR_XFORM_SPARE				0x62fc

/* UVG  (base 0x2a00, absolute 0x6300) */
#define VFE_PP_CLC_UVG_HW_VERSION				0x6300
#define VFE_PP_CLC_UVG_HW_STATUS				0x6304
#define VFE_PP_CLC_UVG_DMI_CFG					0x6308
#define VFE_PP_CLC_UVG_DMI_LUT_CFG				0x630c
#define VFE_PP_CLC_UVG_DMI_DATA					0x6310
#define VFE_PP_CLC_UVG_DMI_CMD					0x6350
#define VFE_PP_CLC_UVG_DMI_STATUS				0x6354
#define VFE_PP_CLC_UVG_DMI_LUT_BANK_CFG				0x6358
#define VFE_PP_CLC_UVG_MODULE_LUT_BANK_CFG			0x635c
#define VFE_PP_CLC_UVG_MODULE_CFG				0x6360
#define VFE_PP_CLC_UVG_TEST_BUS_CTRL				0x64f8
#define VFE_PP_CLC_UVG_SPARE					0x64fc
/* UVG: 15 LUT/DMI entries at 0x6314..0x634c, index with a stride of 4 */

/* PREPROCESSOR  (base 0x2c00, absolute 0x6500) */
#define VFE_PP_CLC_PREPROCESSOR_HW_VERSION			0x6500
#define VFE_PP_CLC_PREPROCESSOR_HW_STATUS			0x6504
#define VFE_PP_CLC_PREPROCESSOR_MODULE_CFG			0x6560
#define VFE_PP_CLC_PREPROCESSOR_TEST_BUS_CTRL			0x66f8
#define VFE_PP_CLC_PREPROCESSOR_SPARE				0x66fc

/* CHROMA_UP  (base 0x2e00, absolute 0x6700) */
#define VFE_PP_CLC_CHROMA_UP_HW_VERSION				0x6700
#define VFE_PP_CLC_CHROMA_UP_HW_STATUS				0x6704
#define VFE_PP_CLC_CHROMA_UP_MODULE_CFG				0x6760
#define VFE_PP_CLC_CHROMA_UP_CHROMA_UP_HSCALE_CFG		0x6768
#define VFE_PP_CLC_CHROMA_UP_CHROMA_UP_OUTPUT_CFG		0x676c
#define VFE_PP_CLC_CHROMA_UP_CROP_LUMA_PIXEL_CFG		0x6770
#define VFE_PP_CLC_CHROMA_UP_CROP_CHROMA_PIXEL_CFG		0x6774
#define VFE_PP_CLC_CHROMA_UP_TEST_BUS_CTRL			0x68f8
#define VFE_PP_CLC_CHROMA_UP_SPARE				0x68fc

/* SPARSE_PD_EXT  (base 0x3000, absolute 0x6900) */
#define VFE_PP_CLC_SPARSE_PD_EXT_HW_VERSION			0x6900
#define VFE_PP_CLC_SPARSE_PD_EXT_HW_STATUS			0x6904
#define VFE_PP_CLC_SPARSE_PD_EXT_MODULE_CFG			0x6960
#define VFE_PP_CLC_SPARSE_PD_EXT_PIXEL_SKIP_PATTERN_CFG		0x6964
#define VFE_PP_CLC_SPARSE_PD_EXT_LINE_SKIP_PATTERN_CFG		0x6968
#define VFE_PP_CLC_SPARSE_PD_EXT_PERIOD_CFG			0x696c
#define VFE_PP_CLC_SPARSE_PD_EXT_CROP_WIDTH_CFG			0x6970
#define VFE_PP_CLC_SPARSE_PD_EXT_CROP_HEIGHT_CFG		0x6974
#define VFE_PP_CLC_SPARSE_PD_EXT_DEBUG				0x6af4
#define VFE_PP_CLC_SPARSE_PD_EXT_TEST_BUS_CTRL			0x6af8
#define VFE_PP_CLC_SPARSE_PD_EXT_SPARE				0x6afc

/* LCR  (base 0x3200, absolute 0x6b00) */
#define VFE_PP_CLC_LCR_HW_VERSION				0x6b00
#define VFE_PP_CLC_LCR_HW_STATUS				0x6b04
#define VFE_PP_CLC_LCR_MODULE_CFG				0x6b60
#define VFE_PP_CLC_LCR_CROP_LINE_CFG				0x6b68
#define VFE_PP_CLC_LCR_CROP_PIXEL_CFG				0x6b6c
#define VFE_PP_CLC_LCR_C_EXT_CFG_0				0x6b70
#define VFE_PP_CLC_LCR_C_EXT_CFG_1				0x6b74
#define VFE_PP_CLC_LCR_C_EXT_CFG_2				0x6b78
#define VFE_PP_CLC_LCR_C_EXT_CFG_3				0x6b7c
#define VFE_PP_CLC_LCR_C_EXT_CFG_4				0x6b80
#define VFE_PP_CLC_LCR_C_EXT_CFG_5				0x6b84
#define VFE_PP_CLC_LCR_TEST_BUS_CTRL				0x6cf8
#define VFE_PP_CLC_LCR_SPARE					0x6cfc

/* COMPDECOMP_HVX_TX  (base 0x3400, absolute 0x6d00) */
#define VFE_PP_CLC_COMPDECOMP_HVX_TX_HW_VERSION			0x6d00
#define VFE_PP_CLC_COMPDECOMP_HVX_TX_HW_STATUS			0x6d04
#define VFE_PP_CLC_COMPDECOMP_HVX_TX_MODULE_CFG			0x6d60
#define VFE_PP_CLC_COMPDECOMP_HVX_TX_KNEE_CFG_0			0x6d68
#define VFE_PP_CLC_COMPDECOMP_HVX_TX_KNEE_CFG_1			0x6d6c
#define VFE_PP_CLC_COMPDECOMP_HVX_TX_KNEE_CFG_2			0x6d70
#define VFE_PP_CLC_COMPDECOMP_HVX_TX_KNEE_CFG_3			0x6d74
#define VFE_PP_CLC_COMPDECOMP_HVX_TX_KNEE_CFG_4			0x6d78
#define VFE_PP_CLC_COMPDECOMP_HVX_TX_KNEE_CFG_5			0x6d7c
#define VFE_PP_CLC_COMPDECOMP_HVX_TX_KNEE_CFG_6			0x6d80
#define VFE_PP_CLC_COMPDECOMP_HVX_TX_KNEE_CFG_7			0x6d84
#define VFE_PP_CLC_COMPDECOMP_HVX_TX_KNEE_CFG_8			0x6d88
#define VFE_PP_CLC_COMPDECOMP_HVX_TX_KNEE_CFG_9			0x6d8c
#define VFE_PP_CLC_COMPDECOMP_HVX_TX_KNEE_CFG_10		0x6d90
#define VFE_PP_CLC_COMPDECOMP_HVX_TX_KNEE_CFG_11		0x6d94
#define VFE_PP_CLC_COMPDECOMP_HVX_TX_KNEE_CFG_12		0x6d98
#define VFE_PP_CLC_COMPDECOMP_HVX_TX_KNEE_CFG_13		0x6d9c
#define VFE_PP_CLC_COMPDECOMP_HVX_TX_KNEE_CFG_14		0x6da0
#define VFE_PP_CLC_COMPDECOMP_HVX_TX_BASE_CFG_0			0x6db4
#define VFE_PP_CLC_COMPDECOMP_HVX_TX_BASE_CFG_1			0x6db8
#define VFE_PP_CLC_COMPDECOMP_HVX_TX_BASE_CFG_2			0x6dbc
#define VFE_PP_CLC_COMPDECOMP_HVX_TX_BASE_CFG_3			0x6dc0
#define VFE_PP_CLC_COMPDECOMP_HVX_TX_BASE_CFG_4			0x6dc4
#define VFE_PP_CLC_COMPDECOMP_HVX_TX_BASE_CFG_5			0x6dc8
#define VFE_PP_CLC_COMPDECOMP_HVX_TX_BASE_CFG_6			0x6dcc
#define VFE_PP_CLC_COMPDECOMP_HVX_TX_BASE_CFG_7			0x6dd0
#define VFE_PP_CLC_COMPDECOMP_HVX_TX_BASE_CFG_8			0x6dd4
#define VFE_PP_CLC_COMPDECOMP_HVX_TX_BASE_CFG_9			0x6dd8
#define VFE_PP_CLC_COMPDECOMP_HVX_TX_BASE_CFG_10		0x6ddc
#define VFE_PP_CLC_COMPDECOMP_HVX_TX_BASE_CFG_11		0x6de0
#define VFE_PP_CLC_COMPDECOMP_HVX_TX_BASE_CFG_12		0x6de4
#define VFE_PP_CLC_COMPDECOMP_HVX_TX_BASE_CFG_13		0x6de8
#define VFE_PP_CLC_COMPDECOMP_HVX_TX_BASE_CFG_14		0x6dec
#define VFE_PP_CLC_COMPDECOMP_HVX_TX_BASE_CFG_15		0x6df0
#define VFE_PP_CLC_COMPDECOMP_HVX_TX_TEST_BUS_CTRL		0x6ef8
#define VFE_PP_CLC_COMPDECOMP_HVX_TX_SPARE			0x6efc
/* COMPDECOMP_HVX_TX: 16 LUT/DMI entries at 0x6e00..0x6e50, index with a stride of 4 */

/* COMPDECOMP_HVX_RX  (base 0x3600, absolute 0x6f00) */
#define VFE_PP_CLC_COMPDECOMP_HVX_RX_HW_VERSION			0x6f00
#define VFE_PP_CLC_COMPDECOMP_HVX_RX_HW_STATUS			0x6f04
#define VFE_PP_CLC_COMPDECOMP_HVX_RX_MODULE_CFG			0x6f60
#define VFE_PP_CLC_COMPDECOMP_HVX_RX_KNEE_CFG_0			0x6f68
#define VFE_PP_CLC_COMPDECOMP_HVX_RX_KNEE_CFG_1			0x6f6c
#define VFE_PP_CLC_COMPDECOMP_HVX_RX_KNEE_CFG_2			0x6f70
#define VFE_PP_CLC_COMPDECOMP_HVX_RX_KNEE_CFG_3			0x6f74
#define VFE_PP_CLC_COMPDECOMP_HVX_RX_KNEE_CFG_4			0x6f78
#define VFE_PP_CLC_COMPDECOMP_HVX_RX_KNEE_CFG_5			0x6f7c
#define VFE_PP_CLC_COMPDECOMP_HVX_RX_KNEE_CFG_6			0x6f80
#define VFE_PP_CLC_COMPDECOMP_HVX_RX_KNEE_CFG_7			0x6f84
#define VFE_PP_CLC_COMPDECOMP_HVX_RX_KNEE_CFG_8			0x6f88
#define VFE_PP_CLC_COMPDECOMP_HVX_RX_KNEE_CFG_9			0x6f8c
#define VFE_PP_CLC_COMPDECOMP_HVX_RX_KNEE_CFG_10		0x6f90
#define VFE_PP_CLC_COMPDECOMP_HVX_RX_KNEE_CFG_11		0x6f94
#define VFE_PP_CLC_COMPDECOMP_HVX_RX_KNEE_CFG_12		0x6f98
#define VFE_PP_CLC_COMPDECOMP_HVX_RX_KNEE_CFG_13		0x6f9c
#define VFE_PP_CLC_COMPDECOMP_HVX_RX_KNEE_CFG_14		0x6fa0
#define VFE_PP_CLC_COMPDECOMP_HVX_RX_BASE_CFG_0			0x6fb4
#define VFE_PP_CLC_COMPDECOMP_HVX_RX_BASE_CFG_1			0x6fb8
#define VFE_PP_CLC_COMPDECOMP_HVX_RX_BASE_CFG_2			0x6fbc
#define VFE_PP_CLC_COMPDECOMP_HVX_RX_BASE_CFG_3			0x6fc0
#define VFE_PP_CLC_COMPDECOMP_HVX_RX_BASE_CFG_4			0x6fc4
#define VFE_PP_CLC_COMPDECOMP_HVX_RX_BASE_CFG_5			0x6fc8
#define VFE_PP_CLC_COMPDECOMP_HVX_RX_BASE_CFG_6			0x6fcc
#define VFE_PP_CLC_COMPDECOMP_HVX_RX_BASE_CFG_7			0x6fd0
#define VFE_PP_CLC_COMPDECOMP_HVX_RX_BASE_CFG_8			0x6fd4
#define VFE_PP_CLC_COMPDECOMP_HVX_RX_BASE_CFG_9			0x6fd8
#define VFE_PP_CLC_COMPDECOMP_HVX_RX_BASE_CFG_10		0x6fdc
#define VFE_PP_CLC_COMPDECOMP_HVX_RX_BASE_CFG_11		0x6fe0
#define VFE_PP_CLC_COMPDECOMP_HVX_RX_BASE_CFG_12		0x6fe4
#define VFE_PP_CLC_COMPDECOMP_HVX_RX_BASE_CFG_13		0x6fe8
#define VFE_PP_CLC_COMPDECOMP_HVX_RX_BASE_CFG_14		0x6fec
#define VFE_PP_CLC_COMPDECOMP_HVX_RX_BASE_CFG_15		0x6ff0
#define VFE_PP_CLC_COMPDECOMP_HVX_RX_TEST_BUS_CTRL		0x70f8
#define VFE_PP_CLC_COMPDECOMP_HVX_RX_SPARE			0x70fc
/* COMPDECOMP_HVX_RX: 16 LUT/DMI entries at 0x7000..0x7050, index with a stride of 4 */

/* GTM_FD_OUT  (base 0x3800, absolute 0x7100) */
#define VFE_PP_CLC_GTM_FD_OUT_HW_VERSION			0x7100
#define VFE_PP_CLC_GTM_FD_OUT_HW_STATUS				0x7104
#define VFE_PP_CLC_GTM_FD_OUT_DMI_CFG				0x7108
#define VFE_PP_CLC_GTM_FD_OUT_DMI_LUT_CFG			0x710c
#define VFE_PP_CLC_GTM_FD_OUT_DMI_DATA				0x7110
#define VFE_PP_CLC_GTM_FD_OUT_DMI_CMD				0x7150
#define VFE_PP_CLC_GTM_FD_OUT_DMI_STATUS			0x7154
#define VFE_PP_CLC_GTM_FD_OUT_DMI_LUT_BANK_CFG			0x7158
#define VFE_PP_CLC_GTM_FD_OUT_MODULE_LUT_BANK_CFG		0x715c
#define VFE_PP_CLC_GTM_FD_OUT_MODULE_CFG			0x7160
#define VFE_PP_CLC_GTM_FD_OUT_C1_COEFF				0x7164
#define VFE_PP_CLC_GTM_FD_OUT_C2_COEFF				0x7168
#define VFE_PP_CLC_GTM_FD_OUT_C3_COEFF				0x716c
#define VFE_PP_CLC_GTM_FD_OUT_C4_COEFF				0x7170
#define VFE_PP_CLC_GTM_FD_OUT_TEST_BUS_CTRL			0x75f8
#define VFE_PP_CLC_GTM_FD_OUT_SPARE				0x75fc
/* GTM_FD_OUT: 271 LUT/DMI entries at 0x7114..0x7570, index with a stride of 4 */

/* CROP_RND_CLAMP_PIXEL_RAW_OUT  (base 0x3d00, absolute 0x7600) */
#define VFE_PP_CLC_CROP_RND_CLAMP_PIXEL_RAW_OUT_HW_VERSION	0x7600
#define VFE_PP_CLC_CROP_RND_CLAMP_PIXEL_RAW_OUT_HW_STATUS	0x7604
#define VFE_PP_CLC_CROP_RND_CLAMP_PIXEL_RAW_OUT_MODULE_CFG	0x7660
#define VFE_PP_CLC_CROP_RND_CLAMP_PIXEL_RAW_OUT_CROP_LINE_CFG	0x7668
#define VFE_PP_CLC_CROP_RND_CLAMP_PIXEL_RAW_OUT_CROP_PIXEL_CFG	0x766c
#define VFE_PP_CLC_CROP_RND_CLAMP_PIXEL_RAW_OUT_CH0_CLAMP_MIN	0x7670
#define VFE_PP_CLC_CROP_RND_CLAMP_PIXEL_RAW_OUT_CH0_ROUNDING_CFG	0x7674
#define VFE_PP_CLC_CROP_RND_CLAMP_PIXEL_RAW_OUT_CH1_CLAMP_MIN	0x7678
#define VFE_PP_CLC_CROP_RND_CLAMP_PIXEL_RAW_OUT_CH1_ROUNDING_CFG	0x767c
#define VFE_PP_CLC_CROP_RND_CLAMP_PIXEL_RAW_OUT_CH2_CLAMP_MIN	0x7680
#define VFE_PP_CLC_CROP_RND_CLAMP_PIXEL_RAW_OUT_CH2_ROUNDING_CFG	0x7684
#define VFE_PP_CLC_CROP_RND_CLAMP_PIXEL_RAW_OUT_CH0_CLAMP_MAX	0x7688
#define VFE_PP_CLC_CROP_RND_CLAMP_PIXEL_RAW_OUT_CH1_CLAMP_MAX	0x768c
#define VFE_PP_CLC_CROP_RND_CLAMP_PIXEL_RAW_OUT_CH2_CLAMP_MAX	0x7690
#define VFE_PP_CLC_CROP_RND_CLAMP_PIXEL_RAW_OUT_UNSIGNED_TO_SIGNED_BPP	0x7694
#define VFE_PP_CLC_CROP_RND_CLAMP_PIXEL_RAW_OUT_TEST_BUS_CTRL	0x77f8
#define VFE_PP_CLC_CROP_RND_CLAMP_PIXEL_RAW_OUT_SPARE		0x77fc

/* DOWNSCALE_MN_Y_FD_OUT  (base 0x3f00, absolute 0x7800) */
#define VFE_PP_CLC_DOWNSCALE_MN_Y_FD_OUT_HW_VERSION		0x7800
#define VFE_PP_CLC_DOWNSCALE_MN_Y_FD_OUT_HW_STATUS		0x7804
#define VFE_PP_CLC_DOWNSCALE_MN_Y_FD_OUT_MODULE_CFG		0x7860
#define VFE_PP_CLC_DOWNSCALE_MN_Y_FD_OUT_DOWNSCALE_MN_Y_CFG	0x7864
#define VFE_PP_CLC_DOWNSCALE_MN_Y_FD_OUT_DOWNSCALE_MN_Y_IMAGE_SIZE_CFG	0x7868
#define VFE_PP_CLC_DOWNSCALE_MN_Y_FD_OUT_DOWNSCALE_MN_Y_H_CFG	0x786c
#define VFE_PP_CLC_DOWNSCALE_MN_Y_FD_OUT_DOWNSCALE_MN_Y_H_PHASE_CFG	0x7870
#define VFE_PP_CLC_DOWNSCALE_MN_Y_FD_OUT_DOWNSCALE_MN_Y_V_CFG	0x7874
#define VFE_PP_CLC_DOWNSCALE_MN_Y_FD_OUT_DOWNSCALE_MN_Y_V_PHASE_CFG	0x7878
#define VFE_PP_CLC_DOWNSCALE_MN_Y_FD_OUT_DOWNSCALE_MN_Y_CROP_LINE_CFG	0x787c
#define VFE_PP_CLC_DOWNSCALE_MN_Y_FD_OUT_DOWNSCALE_MN_Y_CROP_PIXEL_CFG	0x7880
#define VFE_PP_CLC_DOWNSCALE_MN_Y_FD_OUT_DOWNSCALE_MN_Y_OVERLAP	0x7884
#define VFE_PP_CLC_DOWNSCALE_MN_Y_FD_OUT_TEST_BUS_CTRL		0x79f8
#define VFE_PP_CLC_DOWNSCALE_MN_Y_FD_OUT_SPARE			0x79fc

/* DOWNSCALE_MN_C_FD_OUT  (base 0x4100, absolute 0x7a00) */
#define VFE_PP_CLC_DOWNSCALE_MN_C_FD_OUT_HW_VERSION		0x7a00
#define VFE_PP_CLC_DOWNSCALE_MN_C_FD_OUT_HW_STATUS		0x7a04
#define VFE_PP_CLC_DOWNSCALE_MN_C_FD_OUT_MODULE_CFG		0x7a60
#define VFE_PP_CLC_DOWNSCALE_MN_C_FD_OUT_DOWNSCALE_MN_C_CFG	0x7a64
#define VFE_PP_CLC_DOWNSCALE_MN_C_FD_OUT_DOWNSCALE_MN_C_IMAGE_SIZE_CFG	0x7a68
#define VFE_PP_CLC_DOWNSCALE_MN_C_FD_OUT_DOWNSCALE_MN_C_H_CFG	0x7a6c
#define VFE_PP_CLC_DOWNSCALE_MN_C_FD_OUT_DOWNSCALE_MN_C_H_PHASE_CFG	0x7a70
#define VFE_PP_CLC_DOWNSCALE_MN_C_FD_OUT_DOWNSCALE_MN_C_V_CFG	0x7a74
#define VFE_PP_CLC_DOWNSCALE_MN_C_FD_OUT_DOWNSCALE_MN_C_V_PHASE_CFG	0x7a78
#define VFE_PP_CLC_DOWNSCALE_MN_C_FD_OUT_DOWNSCALE_MN_C_CROP_LINE_CFG	0x7a7c
#define VFE_PP_CLC_DOWNSCALE_MN_C_FD_OUT_DOWNSCALE_MN_C_CROP_PIXEL_CFG	0x7a80
#define VFE_PP_CLC_DOWNSCALE_MN_C_FD_OUT_DOWNSCALE_MN_C_OVERLAP	0x7a84
#define VFE_PP_CLC_DOWNSCALE_MN_C_FD_OUT_TEST_BUS_CTRL		0x7bf8
#define VFE_PP_CLC_DOWNSCALE_MN_C_FD_OUT_SPARE			0x7bfc

/* CROP_RND_CLAMP_POST_DOWNSCALE_MN_Y_FD_OUT  (base 0x4300, absolute 0x7c00) */
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_MN_Y_FD_OUT_HW_VERSION	0x7c00
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_MN_Y_FD_OUT_HW_STATUS	0x7c04
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_MN_Y_FD_OUT_MODULE_CFG	0x7c60
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_MN_Y_FD_OUT_CROP_LINE_CFG	0x7c68
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_MN_Y_FD_OUT_CROP_PIXEL_CFG	0x7c6c
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_MN_Y_FD_OUT_CH0_CLAMP_MIN	0x7c70
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_MN_Y_FD_OUT_CH0_ROUNDING_CFG	0x7c74
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_MN_Y_FD_OUT_CH1_CLAMP_MIN	0x7c78
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_MN_Y_FD_OUT_CH1_ROUNDING_CFG	0x7c7c
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_MN_Y_FD_OUT_CH2_CLAMP_MIN	0x7c80
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_MN_Y_FD_OUT_CH2_ROUNDING_CFG	0x7c84
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_MN_Y_FD_OUT_CH0_CLAMP_MAX	0x7c88
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_MN_Y_FD_OUT_CH1_CLAMP_MAX	0x7c8c
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_MN_Y_FD_OUT_CH2_CLAMP_MAX	0x7c90
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_MN_Y_FD_OUT_UNSIGNED_TO_SIGNED_BPP	0x7c94
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_MN_Y_FD_OUT_TEST_BUS_CTRL	0x7df8
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_MN_Y_FD_OUT_SPARE	0x7dfc

/* CROP_RND_CLAMP_POST_DOWNSCALE_MN_C_FD_OUT  (base 0x4500, absolute 0x7e00) */
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_MN_C_FD_OUT_HW_VERSION	0x7e00
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_MN_C_FD_OUT_HW_STATUS	0x7e04
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_MN_C_FD_OUT_MODULE_CFG	0x7e60
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_MN_C_FD_OUT_CROP_LINE_CFG	0x7e68
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_MN_C_FD_OUT_CROP_PIXEL_CFG	0x7e6c
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_MN_C_FD_OUT_CH0_CLAMP_MIN	0x7e70
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_MN_C_FD_OUT_CH0_ROUNDING_CFG	0x7e74
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_MN_C_FD_OUT_CH1_CLAMP_MIN	0x7e78
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_MN_C_FD_OUT_CH1_ROUNDING_CFG	0x7e7c
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_MN_C_FD_OUT_CH2_CLAMP_MIN	0x7e80
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_MN_C_FD_OUT_CH2_ROUNDING_CFG	0x7e84
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_MN_C_FD_OUT_CH0_CLAMP_MAX	0x7e88
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_MN_C_FD_OUT_CH1_CLAMP_MAX	0x7e8c
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_MN_C_FD_OUT_CH2_CLAMP_MAX	0x7e90
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_MN_C_FD_OUT_UNSIGNED_TO_SIGNED_BPP	0x7e94
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_MN_C_FD_OUT_TEST_BUS_CTRL	0x7ff8
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_MN_C_FD_OUT_SPARE	0x7ffc

/* DOWNSCALE_MN_Y_DISP_OUT  (base 0x4700, absolute 0x8000) */
#define VFE_PP_CLC_DOWNSCALE_MN_Y_DISP_OUT_HW_VERSION		0x8000
#define VFE_PP_CLC_DOWNSCALE_MN_Y_DISP_OUT_HW_STATUS		0x8004
#define VFE_PP_CLC_DOWNSCALE_MN_Y_DISP_OUT_MODULE_CFG		0x8060
#define VFE_PP_CLC_DOWNSCALE_MN_Y_DISP_OUT_DOWNSCALE_MN_Y_CFG	0x8064
#define VFE_PP_CLC_DOWNSCALE_MN_Y_DISP_OUT_DOWNSCALE_MN_Y_IMAGE_SIZE_CFG	0x8068
#define VFE_PP_CLC_DOWNSCALE_MN_Y_DISP_OUT_DOWNSCALE_MN_Y_H_CFG	0x806c
#define VFE_PP_CLC_DOWNSCALE_MN_Y_DISP_OUT_DOWNSCALE_MN_Y_H_PHASE_CFG	0x8070
#define VFE_PP_CLC_DOWNSCALE_MN_Y_DISP_OUT_DOWNSCALE_MN_Y_V_CFG	0x8074
#define VFE_PP_CLC_DOWNSCALE_MN_Y_DISP_OUT_DOWNSCALE_MN_Y_V_PHASE_CFG	0x8078
#define VFE_PP_CLC_DOWNSCALE_MN_Y_DISP_OUT_DOWNSCALE_MN_Y_CROP_LINE_CFG	0x807c
#define VFE_PP_CLC_DOWNSCALE_MN_Y_DISP_OUT_DOWNSCALE_MN_Y_CROP_PIXEL_CFG	0x8080
#define VFE_PP_CLC_DOWNSCALE_MN_Y_DISP_OUT_DOWNSCALE_MN_Y_OVERLAP	0x8084
#define VFE_PP_CLC_DOWNSCALE_MN_Y_DISP_OUT_TEST_BUS_CTRL	0x81f8
#define VFE_PP_CLC_DOWNSCALE_MN_Y_DISP_OUT_SPARE		0x81fc

/* DOWNSCALE_MN_C_DISP_OUT  (base 0x4900, absolute 0x8200) */
#define VFE_PP_CLC_DOWNSCALE_MN_C_DISP_OUT_HW_VERSION		0x8200
#define VFE_PP_CLC_DOWNSCALE_MN_C_DISP_OUT_HW_STATUS		0x8204
#define VFE_PP_CLC_DOWNSCALE_MN_C_DISP_OUT_MODULE_CFG		0x8260
#define VFE_PP_CLC_DOWNSCALE_MN_C_DISP_OUT_DOWNSCALE_MN_C_CFG	0x8264
#define VFE_PP_CLC_DOWNSCALE_MN_C_DISP_OUT_DOWNSCALE_MN_C_IMAGE_SIZE_CFG	0x8268
#define VFE_PP_CLC_DOWNSCALE_MN_C_DISP_OUT_DOWNSCALE_MN_C_H_CFG	0x826c
#define VFE_PP_CLC_DOWNSCALE_MN_C_DISP_OUT_DOWNSCALE_MN_C_H_PHASE_CFG	0x8270
#define VFE_PP_CLC_DOWNSCALE_MN_C_DISP_OUT_DOWNSCALE_MN_C_V_CFG	0x8274
#define VFE_PP_CLC_DOWNSCALE_MN_C_DISP_OUT_DOWNSCALE_MN_C_V_PHASE_CFG	0x8278
#define VFE_PP_CLC_DOWNSCALE_MN_C_DISP_OUT_DOWNSCALE_MN_C_CROP_LINE_CFG	0x827c
#define VFE_PP_CLC_DOWNSCALE_MN_C_DISP_OUT_DOWNSCALE_MN_C_CROP_PIXEL_CFG	0x8280
#define VFE_PP_CLC_DOWNSCALE_MN_C_DISP_OUT_DOWNSCALE_MN_C_OVERLAP	0x8284
#define VFE_PP_CLC_DOWNSCALE_MN_C_DISP_OUT_TEST_BUS_CTRL	0x83f8
#define VFE_PP_CLC_DOWNSCALE_MN_C_DISP_OUT_SPARE		0x83fc

/* CROP_RND_CLAMP_POST_DOWNSCALE_MN_Y_DISP_OUT  (base 0x4b00, absolute 0x8400) */
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_MN_Y_DISP_OUT_HW_VERSION	0x8400
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_MN_Y_DISP_OUT_HW_STATUS	0x8404
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_MN_Y_DISP_OUT_MODULE_CFG	0x8460
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_MN_Y_DISP_OUT_CROP_LINE_CFG	0x8468
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_MN_Y_DISP_OUT_CROP_PIXEL_CFG	0x846c
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_MN_Y_DISP_OUT_CH0_CLAMP_MIN	0x8470
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_MN_Y_DISP_OUT_CH0_ROUNDING_CFG	0x8474
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_MN_Y_DISP_OUT_CH1_CLAMP_MIN	0x8478
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_MN_Y_DISP_OUT_CH1_ROUNDING_CFG	0x847c
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_MN_Y_DISP_OUT_CH2_CLAMP_MIN	0x8480
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_MN_Y_DISP_OUT_CH2_ROUNDING_CFG	0x8484
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_MN_Y_DISP_OUT_CH0_CLAMP_MAX	0x8488
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_MN_Y_DISP_OUT_CH1_CLAMP_MAX	0x848c
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_MN_Y_DISP_OUT_CH2_CLAMP_MAX	0x8490
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_MN_Y_DISP_OUT_UNSIGNED_TO_SIGNED_BPP	0x8494
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_MN_Y_DISP_OUT_TEST_BUS_CTRL	0x85f8
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_MN_Y_DISP_OUT_SPARE	0x85fc

/* CROP_RND_CLAMP_POST_DOWNSCALE_MN_C_DISP_OUT  (base 0x4d00, absolute 0x8600) */
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_MN_C_DISP_OUT_HW_VERSION	0x8600
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_MN_C_DISP_OUT_HW_STATUS	0x8604
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_MN_C_DISP_OUT_MODULE_CFG	0x8660
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_MN_C_DISP_OUT_CROP_LINE_CFG	0x8668
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_MN_C_DISP_OUT_CROP_PIXEL_CFG	0x866c
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_MN_C_DISP_OUT_CH0_CLAMP_MIN	0x8670
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_MN_C_DISP_OUT_CH0_ROUNDING_CFG	0x8674
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_MN_C_DISP_OUT_CH1_CLAMP_MIN	0x8678
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_MN_C_DISP_OUT_CH1_ROUNDING_CFG	0x867c
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_MN_C_DISP_OUT_CH2_CLAMP_MIN	0x8680
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_MN_C_DISP_OUT_CH2_ROUNDING_CFG	0x8684
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_MN_C_DISP_OUT_CH0_CLAMP_MAX	0x8688
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_MN_C_DISP_OUT_CH1_CLAMP_MAX	0x868c
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_MN_C_DISP_OUT_CH2_CLAMP_MAX	0x8690
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_MN_C_DISP_OUT_UNSIGNED_TO_SIGNED_BPP	0x8694
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_MN_C_DISP_OUT_TEST_BUS_CTRL	0x87f8
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_MN_C_DISP_OUT_SPARE	0x87fc

/* DOWNSCALE_4TO1_Y_DISP_DS4_OUT  (base 0x4f00, absolute 0x8800) */
#define VFE_PP_CLC_DOWNSCALE_4TO1_Y_DISP_DS4_OUT_HW_VERSION	0x8800
#define VFE_PP_CLC_DOWNSCALE_4TO1_Y_DISP_DS4_OUT_HW_STATUS	0x8804
#define VFE_PP_CLC_DOWNSCALE_4TO1_Y_DISP_DS4_OUT_MODULE_CFG	0x8860
#define VFE_PP_CLC_DOWNSCALE_4TO1_Y_DISP_DS4_OUT_DS_COEFF	0x8868
#define VFE_PP_CLC_DOWNSCALE_4TO1_Y_DISP_DS4_OUT_CROP_LINE_CFG	0x8904
#define VFE_PP_CLC_DOWNSCALE_4TO1_Y_DISP_DS4_OUT_CROP_PIXEL_CFG	0x8908
#define VFE_PP_CLC_DOWNSCALE_4TO1_Y_DISP_DS4_OUT_TEST_BUS_CTRL	0x89f8
#define VFE_PP_CLC_DOWNSCALE_4TO1_Y_DISP_DS4_OUT_SPARE		0x89fc

/* DOWNSCALE_4TO1_C_DISP_DS4_OUT  (base 0x5100, absolute 0x8a00) */
#define VFE_PP_CLC_DOWNSCALE_4TO1_C_DISP_DS4_OUT_HW_VERSION	0x8a00
#define VFE_PP_CLC_DOWNSCALE_4TO1_C_DISP_DS4_OUT_HW_STATUS	0x8a04
#define VFE_PP_CLC_DOWNSCALE_4TO1_C_DISP_DS4_OUT_MODULE_CFG	0x8a60
#define VFE_PP_CLC_DOWNSCALE_4TO1_C_DISP_DS4_OUT_CROP_LINE_CFG	0x8b04
#define VFE_PP_CLC_DOWNSCALE_4TO1_C_DISP_DS4_OUT_CROP_PIXEL_CFG	0x8b08
#define VFE_PP_CLC_DOWNSCALE_4TO1_C_DISP_DS4_OUT_TEST_BUS_CTRL	0x8bf8
#define VFE_PP_CLC_DOWNSCALE_4TO1_C_DISP_DS4_OUT_SPARE		0x8bfc

/* CROP_RND_CLAMP_POST_DOWNSCALE_4TO1_Y_DISP_DS4_OUT  (base 0x5300, absolute 0x8c00) */
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_4TO1_Y_DISP_DS4_OUT_HW_VERSION	0x8c00
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_4TO1_Y_DISP_DS4_OUT_HW_STATUS	0x8c04
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_4TO1_Y_DISP_DS4_OUT_MODULE_CFG	0x8c60
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_4TO1_Y_DISP_DS4_OUT_CROP_LINE_CFG	0x8c68
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_4TO1_Y_DISP_DS4_OUT_CROP_PIXEL_CFG	0x8c6c
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_4TO1_Y_DISP_DS4_OUT_CH0_CLAMP_MIN	0x8c70
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_4TO1_Y_DISP_DS4_OUT_CH0_ROUNDING_CFG	0x8c74
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_4TO1_Y_DISP_DS4_OUT_CH1_CLAMP_MIN	0x8c78
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_4TO1_Y_DISP_DS4_OUT_CH1_ROUNDING_CFG	0x8c7c
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_4TO1_Y_DISP_DS4_OUT_CH2_CLAMP_MIN	0x8c80
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_4TO1_Y_DISP_DS4_OUT_CH2_ROUNDING_CFG	0x8c84
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_4TO1_Y_DISP_DS4_OUT_CH0_CLAMP_MAX	0x8c88
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_4TO1_Y_DISP_DS4_OUT_CH1_CLAMP_MAX	0x8c8c
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_4TO1_Y_DISP_DS4_OUT_CH2_CLAMP_MAX	0x8c90
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_4TO1_Y_DISP_DS4_OUT_UNSIGNED_TO_SIGNED_BPP	0x8c94
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_4TO1_Y_DISP_DS4_OUT_TEST_BUS_CTRL	0x8df8
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_4TO1_Y_DISP_DS4_OUT_SPARE	0x8dfc

/* CROP_RND_CLAMP_POST_DOWNSCALE_4TO1_C_DISP_DS4_OUT  (base 0x5500, absolute 0x8e00) */
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_4TO1_C_DISP_DS4_OUT_HW_VERSION	0x8e00
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_4TO1_C_DISP_DS4_OUT_HW_STATUS	0x8e04
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_4TO1_C_DISP_DS4_OUT_MODULE_CFG	0x8e60
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_4TO1_C_DISP_DS4_OUT_CROP_LINE_CFG	0x8e68
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_4TO1_C_DISP_DS4_OUT_CROP_PIXEL_CFG	0x8e6c
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_4TO1_C_DISP_DS4_OUT_CH0_CLAMP_MIN	0x8e70
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_4TO1_C_DISP_DS4_OUT_CH0_ROUNDING_CFG	0x8e74
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_4TO1_C_DISP_DS4_OUT_CH1_CLAMP_MIN	0x8e78
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_4TO1_C_DISP_DS4_OUT_CH1_ROUNDING_CFG	0x8e7c
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_4TO1_C_DISP_DS4_OUT_CH2_CLAMP_MIN	0x8e80
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_4TO1_C_DISP_DS4_OUT_CH2_ROUNDING_CFG	0x8e84
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_4TO1_C_DISP_DS4_OUT_CH0_CLAMP_MAX	0x8e88
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_4TO1_C_DISP_DS4_OUT_CH1_CLAMP_MAX	0x8e8c
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_4TO1_C_DISP_DS4_OUT_CH2_CLAMP_MAX	0x8e90
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_4TO1_C_DISP_DS4_OUT_UNSIGNED_TO_SIGNED_BPP	0x8e94
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_4TO1_C_DISP_DS4_OUT_TEST_BUS_CTRL	0x8ff8
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_4TO1_C_DISP_DS4_OUT_SPARE	0x8ffc

/* DOWNSCALE_4TO1_Y_DISP_DS16_OUT  (base 0x5700, absolute 0x9000) */
#define VFE_PP_CLC_DOWNSCALE_4TO1_Y_DISP_DS16_OUT_HW_VERSION	0x9000
#define VFE_PP_CLC_DOWNSCALE_4TO1_Y_DISP_DS16_OUT_HW_STATUS	0x9004
#define VFE_PP_CLC_DOWNSCALE_4TO1_Y_DISP_DS16_OUT_MODULE_CFG	0x9060
#define VFE_PP_CLC_DOWNSCALE_4TO1_Y_DISP_DS16_OUT_DS_COEFF	0x9068
#define VFE_PP_CLC_DOWNSCALE_4TO1_Y_DISP_DS16_OUT_CROP_LINE_CFG	0x9104
#define VFE_PP_CLC_DOWNSCALE_4TO1_Y_DISP_DS16_OUT_CROP_PIXEL_CFG	0x9108
#define VFE_PP_CLC_DOWNSCALE_4TO1_Y_DISP_DS16_OUT_TEST_BUS_CTRL	0x91f8
#define VFE_PP_CLC_DOWNSCALE_4TO1_Y_DISP_DS16_OUT_SPARE		0x91fc

/* DOWNSCALE_4TO1_C_DISP_DS16_OUT  (base 0x5900, absolute 0x9200) */
#define VFE_PP_CLC_DOWNSCALE_4TO1_C_DISP_DS16_OUT_HW_VERSION	0x9200
#define VFE_PP_CLC_DOWNSCALE_4TO1_C_DISP_DS16_OUT_HW_STATUS	0x9204
#define VFE_PP_CLC_DOWNSCALE_4TO1_C_DISP_DS16_OUT_MODULE_CFG	0x9260
#define VFE_PP_CLC_DOWNSCALE_4TO1_C_DISP_DS16_OUT_CROP_LINE_CFG	0x9304
#define VFE_PP_CLC_DOWNSCALE_4TO1_C_DISP_DS16_OUT_CROP_PIXEL_CFG	0x9308
#define VFE_PP_CLC_DOWNSCALE_4TO1_C_DISP_DS16_OUT_TEST_BUS_CTRL	0x93f8
#define VFE_PP_CLC_DOWNSCALE_4TO1_C_DISP_DS16_OUT_SPARE		0x93fc

/* CROP_RND_CLAMP_POST_DOWNSCALE_4TO1_Y_DISP_DS16_OUT  (base 0x5b00, absolute 0x9400) */
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_4TO1_Y_DISP_DS16_OUT_HW_VERSION	0x9400
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_4TO1_Y_DISP_DS16_OUT_HW_STATUS	0x9404
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_4TO1_Y_DISP_DS16_OUT_MODULE_CFG	0x9460
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_4TO1_Y_DISP_DS16_OUT_CROP_LINE_CFG	0x9468
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_4TO1_Y_DISP_DS16_OUT_CROP_PIXEL_CFG	0x946c
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_4TO1_Y_DISP_DS16_OUT_CH0_CLAMP_MIN	0x9470
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_4TO1_Y_DISP_DS16_OUT_CH0_ROUNDING_CFG	0x9474
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_4TO1_Y_DISP_DS16_OUT_CH1_CLAMP_MIN	0x9478
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_4TO1_Y_DISP_DS16_OUT_CH1_ROUNDING_CFG	0x947c
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_4TO1_Y_DISP_DS16_OUT_CH2_CLAMP_MIN	0x9480
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_4TO1_Y_DISP_DS16_OUT_CH2_ROUNDING_CFG	0x9484
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_4TO1_Y_DISP_DS16_OUT_CH0_CLAMP_MAX	0x9488
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_4TO1_Y_DISP_DS16_OUT_CH1_CLAMP_MAX	0x948c
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_4TO1_Y_DISP_DS16_OUT_CH2_CLAMP_MAX	0x9490
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_4TO1_Y_DISP_DS16_OUT_UNSIGNED_TO_SIGNED_BPP	0x9494
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_4TO1_Y_DISP_DS16_OUT_TEST_BUS_CTRL	0x95f8
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_4TO1_Y_DISP_DS16_OUT_SPARE	0x95fc

/* CROP_RND_CLAMP_POST_DOWNSCALE_4TO1_C_DISP_DS16_OUT  (base 0x5d00, absolute 0x9600) */
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_4TO1_C_DISP_DS16_OUT_HW_VERSION	0x9600
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_4TO1_C_DISP_DS16_OUT_HW_STATUS	0x9604
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_4TO1_C_DISP_DS16_OUT_MODULE_CFG	0x9660
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_4TO1_C_DISP_DS16_OUT_CROP_LINE_CFG	0x9668
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_4TO1_C_DISP_DS16_OUT_CROP_PIXEL_CFG	0x966c
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_4TO1_C_DISP_DS16_OUT_CH0_CLAMP_MIN	0x9670
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_4TO1_C_DISP_DS16_OUT_CH0_ROUNDING_CFG	0x9674
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_4TO1_C_DISP_DS16_OUT_CH1_CLAMP_MIN	0x9678
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_4TO1_C_DISP_DS16_OUT_CH1_ROUNDING_CFG	0x967c
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_4TO1_C_DISP_DS16_OUT_CH2_CLAMP_MIN	0x9680
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_4TO1_C_DISP_DS16_OUT_CH2_ROUNDING_CFG	0x9684
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_4TO1_C_DISP_DS16_OUT_CH0_CLAMP_MAX	0x9688
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_4TO1_C_DISP_DS16_OUT_CH1_CLAMP_MAX	0x968c
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_4TO1_C_DISP_DS16_OUT_CH2_CLAMP_MAX	0x9690
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_4TO1_C_DISP_DS16_OUT_UNSIGNED_TO_SIGNED_BPP	0x9694
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_4TO1_C_DISP_DS16_OUT_TEST_BUS_CTRL	0x97f8
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_4TO1_C_DISP_DS16_OUT_SPARE	0x97fc

/* DOWNSCALE_MN_Y_VID_OUT  (base 0x5f00, absolute 0x9800) */
#define VFE_PP_CLC_DOWNSCALE_MN_Y_VID_OUT_HW_VERSION		0x9800
#define VFE_PP_CLC_DOWNSCALE_MN_Y_VID_OUT_HW_STATUS		0x9804
#define VFE_PP_CLC_DOWNSCALE_MN_Y_VID_OUT_MODULE_CFG		0x9860
#define VFE_PP_CLC_DOWNSCALE_MN_Y_VID_OUT_DOWNSCALE_MN_Y_CFG	0x9864
#define VFE_PP_CLC_DOWNSCALE_MN_Y_VID_OUT_DOWNSCALE_MN_Y_IMAGE_SIZE_CFG	0x9868
#define VFE_PP_CLC_DOWNSCALE_MN_Y_VID_OUT_DOWNSCALE_MN_Y_H_CFG	0x986c
#define VFE_PP_CLC_DOWNSCALE_MN_Y_VID_OUT_DOWNSCALE_MN_Y_H_PHASE_CFG	0x9870
#define VFE_PP_CLC_DOWNSCALE_MN_Y_VID_OUT_DOWNSCALE_MN_Y_V_CFG	0x9874
#define VFE_PP_CLC_DOWNSCALE_MN_Y_VID_OUT_DOWNSCALE_MN_Y_V_PHASE_CFG	0x9878
#define VFE_PP_CLC_DOWNSCALE_MN_Y_VID_OUT_DOWNSCALE_MN_Y_CROP_LINE_CFG	0x987c
#define VFE_PP_CLC_DOWNSCALE_MN_Y_VID_OUT_DOWNSCALE_MN_Y_CROP_PIXEL_CFG	0x9880
#define VFE_PP_CLC_DOWNSCALE_MN_Y_VID_OUT_DOWNSCALE_MN_Y_OVERLAP	0x9884
#define VFE_PP_CLC_DOWNSCALE_MN_Y_VID_OUT_TEST_BUS_CTRL		0x99f8
#define VFE_PP_CLC_DOWNSCALE_MN_Y_VID_OUT_SPARE			0x99fc

/* DOWNSCALE_MN_C_VID_OUT  (base 0x6100, absolute 0x9a00) */
#define VFE_PP_CLC_DOWNSCALE_MN_C_VID_OUT_HW_VERSION		0x9a00
#define VFE_PP_CLC_DOWNSCALE_MN_C_VID_OUT_HW_STATUS		0x9a04
#define VFE_PP_CLC_DOWNSCALE_MN_C_VID_OUT_MODULE_CFG		0x9a60
#define VFE_PP_CLC_DOWNSCALE_MN_C_VID_OUT_DOWNSCALE_MN_C_CFG	0x9a64
#define VFE_PP_CLC_DOWNSCALE_MN_C_VID_OUT_DOWNSCALE_MN_C_IMAGE_SIZE_CFG	0x9a68
#define VFE_PP_CLC_DOWNSCALE_MN_C_VID_OUT_DOWNSCALE_MN_C_H_CFG	0x9a6c
#define VFE_PP_CLC_DOWNSCALE_MN_C_VID_OUT_DOWNSCALE_MN_C_H_PHASE_CFG	0x9a70
#define VFE_PP_CLC_DOWNSCALE_MN_C_VID_OUT_DOWNSCALE_MN_C_V_CFG	0x9a74
#define VFE_PP_CLC_DOWNSCALE_MN_C_VID_OUT_DOWNSCALE_MN_C_V_PHASE_CFG	0x9a78
#define VFE_PP_CLC_DOWNSCALE_MN_C_VID_OUT_DOWNSCALE_MN_C_CROP_LINE_CFG	0x9a7c
#define VFE_PP_CLC_DOWNSCALE_MN_C_VID_OUT_DOWNSCALE_MN_C_CROP_PIXEL_CFG	0x9a80
#define VFE_PP_CLC_DOWNSCALE_MN_C_VID_OUT_DOWNSCALE_MN_C_OVERLAP	0x9a84
#define VFE_PP_CLC_DOWNSCALE_MN_C_VID_OUT_TEST_BUS_CTRL		0x9bf8
#define VFE_PP_CLC_DOWNSCALE_MN_C_VID_OUT_SPARE			0x9bfc

/* CROP_RND_CLAMP_POST_DOWNSCALE_MN_Y_VID_OUT  (base 0x6300, absolute 0x9c00) */
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_MN_Y_VID_OUT_HW_VERSION	0x9c00
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_MN_Y_VID_OUT_HW_STATUS	0x9c04
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_MN_Y_VID_OUT_MODULE_CFG	0x9c60
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_MN_Y_VID_OUT_CROP_LINE_CFG	0x9c68
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_MN_Y_VID_OUT_CROP_PIXEL_CFG	0x9c6c
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_MN_Y_VID_OUT_CH0_CLAMP_MIN	0x9c70
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_MN_Y_VID_OUT_CH0_ROUNDING_CFG	0x9c74
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_MN_Y_VID_OUT_CH1_CLAMP_MIN	0x9c78
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_MN_Y_VID_OUT_CH1_ROUNDING_CFG	0x9c7c
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_MN_Y_VID_OUT_CH2_CLAMP_MIN	0x9c80
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_MN_Y_VID_OUT_CH2_ROUNDING_CFG	0x9c84
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_MN_Y_VID_OUT_CH0_CLAMP_MAX	0x9c88
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_MN_Y_VID_OUT_CH1_CLAMP_MAX	0x9c8c
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_MN_Y_VID_OUT_CH2_CLAMP_MAX	0x9c90
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_MN_Y_VID_OUT_UNSIGNED_TO_SIGNED_BPP	0x9c94
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_MN_Y_VID_OUT_TEST_BUS_CTRL	0x9df8
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_MN_Y_VID_OUT_SPARE	0x9dfc

/* CROP_RND_CLAMP_POST_DOWNSCALE_MN_C_VID_OUT  (base 0x6500, absolute 0x9e00) */
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_MN_C_VID_OUT_HW_VERSION	0x9e00
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_MN_C_VID_OUT_HW_STATUS	0x9e04
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_MN_C_VID_OUT_MODULE_CFG	0x9e60
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_MN_C_VID_OUT_CROP_LINE_CFG	0x9e68
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_MN_C_VID_OUT_CROP_PIXEL_CFG	0x9e6c
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_MN_C_VID_OUT_CH0_CLAMP_MIN	0x9e70
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_MN_C_VID_OUT_CH0_ROUNDING_CFG	0x9e74
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_MN_C_VID_OUT_CH1_CLAMP_MIN	0x9e78
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_MN_C_VID_OUT_CH1_ROUNDING_CFG	0x9e7c
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_MN_C_VID_OUT_CH2_CLAMP_MIN	0x9e80
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_MN_C_VID_OUT_CH2_ROUNDING_CFG	0x9e84
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_MN_C_VID_OUT_CH0_CLAMP_MAX	0x9e88
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_MN_C_VID_OUT_CH1_CLAMP_MAX	0x9e8c
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_MN_C_VID_OUT_CH2_CLAMP_MAX	0x9e90
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_MN_C_VID_OUT_UNSIGNED_TO_SIGNED_BPP	0x9e94
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_MN_C_VID_OUT_TEST_BUS_CTRL	0x9ff8
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_MN_C_VID_OUT_SPARE	0x9ffc

/* DSX_Y_VID_OUT  (base 0x6700, absolute 0xa000) */
#define VFE_PP_CLC_DSX_Y_VID_OUT_HW_VERSION			0xa000
#define VFE_PP_CLC_DSX_Y_VID_OUT_HW_STATUS			0xa004
#define VFE_PP_CLC_DSX_Y_VID_OUT_DMI_CFG			0xa008
#define VFE_PP_CLC_DSX_Y_VID_OUT_DMI_LUT_CFG			0xa00c
#define VFE_PP_CLC_DSX_Y_VID_OUT_DMI_DATA			0xa010
#define VFE_PP_CLC_DSX_Y_VID_OUT_DMI_CMD			0xa050
#define VFE_PP_CLC_DSX_Y_VID_OUT_DMI_STATUS			0xa054
#define VFE_PP_CLC_DSX_Y_VID_OUT_DMI_LUT_BANK_CFG		0xa058
#define VFE_PP_CLC_DSX_Y_VID_OUT_MODULE_LUT_BANK_CFG		0xa05c
#define VFE_PP_CLC_DSX_Y_VID_OUT_MODULE_CFG			0xa060
#define VFE_PP_CLC_DSX_Y_VID_OUT_MODE				0xa064
#define VFE_PP_CLC_DSX_Y_VID_OUT_START_LOCATION_X		0xa068
#define VFE_PP_CLC_DSX_Y_VID_OUT_START_LOCATION_Y		0xa06c
#define VFE_PP_CLC_DSX_Y_VID_OUT_SCALE_RATIO_X			0xa070
#define VFE_PP_CLC_DSX_Y_VID_OUT_SCALE_RATIO_Y			0xa074
#define VFE_PP_CLC_DSX_Y_VID_OUT_OUT_SIZE			0xa078
#define VFE_PP_CLC_DSX_Y_VID_OUT_IN_SIZE			0xa07c
#define VFE_PP_CLC_DSX_Y_VID_OUT_PADDING_WEIGHTS_TOP_BOT_LUMA_0	0xa080
#define VFE_PP_CLC_DSX_Y_VID_OUT_PADDING_WEIGHTS_TOP_BOT_LUMA_1	0xa084
#define VFE_PP_CLC_DSX_Y_VID_OUT_PADDING_WEIGHTS_TOP_BOT_LUMA_2	0xa088
#define VFE_PP_CLC_DSX_Y_VID_OUT_PADDING_WEIGHTS_TOP_BOT_LUMA_3	0xa08c
#define VFE_PP_CLC_DSX_Y_VID_OUT_PADDING_WEIGHTS_TOP_BOT_LUMA_4	0xa090
#define VFE_PP_CLC_DSX_Y_VID_OUT_PADDING_WEIGHTS_TOP_BOT_LUMA_5	0xa094
#define VFE_PP_CLC_DSX_Y_VID_OUT_PADDING_WEIGHTS_TOP_BOT_LUMA_6	0xa098
#define VFE_PP_CLC_DSX_Y_VID_OUT_PADDING_WEIGHTS_TOP_BOT_LUMA_7	0xa09c
#define VFE_PP_CLC_DSX_Y_VID_OUT_PADDING_WEIGHTS_TOP_BOT_LUMA_8	0xa0a0
#define VFE_PP_CLC_DSX_Y_VID_OUT_PADDING_WEIGHTS_TOP_BOT_LUMA_9	0xa0a4
#define VFE_PP_CLC_DSX_Y_VID_OUT_PADDING_WEIGHTS_TOP_BOT_LUMA_10	0xa0a8
#define VFE_PP_CLC_DSX_Y_VID_OUT_PADDING_WEIGHTS_TOP_BOT_LUMA_11	0xa0ac
#define VFE_PP_CLC_DSX_Y_VID_OUT_PADDING_WEIGHTS_TOP_BOT_LUMA_12	0xa0b0
#define VFE_PP_CLC_DSX_Y_VID_OUT_PADDING_WEIGHTS_TOP_BOT_LUMA_13	0xa0b4
#define VFE_PP_CLC_DSX_Y_VID_OUT_PADDING_WEIGHTS_TOP_BOT_LUMA_14	0xa0b8
#define VFE_PP_CLC_DSX_Y_VID_OUT_PADDING_WEIGHTS_TOP_BOT_LUMA_15	0xa0bc
#define VFE_PP_CLC_DSX_Y_VID_OUT_PADDING_WEIGHTS_TOP_BOT_LUMA_16	0xa0c0
#define VFE_PP_CLC_DSX_Y_VID_OUT_PADDING_WEIGHTS_TOP_BOT_LUMA_17	0xa0c4
#define VFE_PP_CLC_DSX_Y_VID_OUT_PADDING_WEIGHTS_TOP_BOT_LUMA_18	0xa0c8
#define VFE_PP_CLC_DSX_Y_VID_OUT_PADDING_WEIGHTS_TOP_BOT_LUMA_19	0xa0cc
#define VFE_PP_CLC_DSX_Y_VID_OUT_PADDING_WEIGHTS_TOP_BOT_LUMA_20	0xa0d0
#define VFE_PP_CLC_DSX_Y_VID_OUT_PADDING_WEIGHTS_TOP_BOT_LUMA_21	0xa0d4
#define VFE_PP_CLC_DSX_Y_VID_OUT_PADDING_WEIGHTS_TOP_BOT_LUMA_22	0xa0d8
#define VFE_PP_CLC_DSX_Y_VID_OUT_PADDING_WEIGHTS_TOP_BOT_LUMA_23	0xa0dc
#define VFE_PP_CLC_DSX_Y_VID_OUT_PADDING_WEIGHTS_LEFT_RGT_LUMA_0	0xa100
#define VFE_PP_CLC_DSX_Y_VID_OUT_PADDING_WEIGHTS_LEFT_RGT_LUMA_1	0xa104
#define VFE_PP_CLC_DSX_Y_VID_OUT_PADDING_WEIGHTS_LEFT_RGT_LUMA_2	0xa108
#define VFE_PP_CLC_DSX_Y_VID_OUT_PADDING_WEIGHTS_LEFT_RGT_LUMA_3	0xa10c
#define VFE_PP_CLC_DSX_Y_VID_OUT_PADDING_WEIGHTS_LEFT_RGT_LUMA_4	0xa110
#define VFE_PP_CLC_DSX_Y_VID_OUT_PADDING_WEIGHTS_LEFT_RGT_LUMA_5	0xa114
#define VFE_PP_CLC_DSX_Y_VID_OUT_PADDING_WEIGHTS_LEFT_RGT_LUMA_6	0xa118
#define VFE_PP_CLC_DSX_Y_VID_OUT_PADDING_WEIGHTS_LEFT_RGT_LUMA_7	0xa11c
#define VFE_PP_CLC_DSX_Y_VID_OUT_PADDING_WEIGHTS_LEFT_RGT_LUMA_8	0xa120
#define VFE_PP_CLC_DSX_Y_VID_OUT_PADDING_WEIGHTS_LEFT_RGT_LUMA_9	0xa124
#define VFE_PP_CLC_DSX_Y_VID_OUT_PADDING_WEIGHTS_LEFT_RGT_LUMA_10	0xa128
#define VFE_PP_CLC_DSX_Y_VID_OUT_PADDING_WEIGHTS_LEFT_RGT_LUMA_11	0xa12c
#define VFE_PP_CLC_DSX_Y_VID_OUT_PADDING_WEIGHTS_LEFT_RGT_LUMA_12	0xa130
#define VFE_PP_CLC_DSX_Y_VID_OUT_PADDING_WEIGHTS_LEFT_RGT_LUMA_13	0xa134
#define VFE_PP_CLC_DSX_Y_VID_OUT_PADDING_WEIGHTS_LEFT_RGT_LUMA_14	0xa138
#define VFE_PP_CLC_DSX_Y_VID_OUT_PADDING_WEIGHTS_LEFT_RGT_LUMA_15	0xa13c
#define VFE_PP_CLC_DSX_Y_VID_OUT_PADDING_WEIGHTS_LEFT_RGT_LUMA_16	0xa140
#define VFE_PP_CLC_DSX_Y_VID_OUT_PADDING_WEIGHTS_LEFT_RGT_LUMA_17	0xa144
#define VFE_PP_CLC_DSX_Y_VID_OUT_PADDING_WEIGHTS_LEFT_RGT_LUMA_18	0xa148
#define VFE_PP_CLC_DSX_Y_VID_OUT_PADDING_WEIGHTS_LEFT_RGT_LUMA_19	0xa14c
#define VFE_PP_CLC_DSX_Y_VID_OUT_PADDING_WEIGHTS_LEFT_RGT_LUMA_20	0xa150
#define VFE_PP_CLC_DSX_Y_VID_OUT_PADDING_WEIGHTS_LEFT_RGT_LUMA_21	0xa154
#define VFE_PP_CLC_DSX_Y_VID_OUT_PADDING_WEIGHTS_LEFT_RGT_LUMA_22	0xa158
#define VFE_PP_CLC_DSX_Y_VID_OUT_PADDING_WEIGHTS_LEFT_RGT_LUMA_23	0xa15c
#define VFE_PP_CLC_DSX_Y_VID_OUT_TEST_BUS_CTRL			0xa1f8
#define VFE_PP_CLC_DSX_Y_VID_OUT_SPARE				0xa1fc
/* DSX_Y_VID_OUT: 15 LUT/DMI entries at 0xa014..0xa04c, index with a stride of 4 */

/* DSX_C_VID_OUT  (base 0x6900, absolute 0xa200) */
#define VFE_PP_CLC_DSX_C_VID_OUT_HW_VERSION			0xa200
#define VFE_PP_CLC_DSX_C_VID_OUT_HW_STATUS			0xa204
#define VFE_PP_CLC_DSX_C_VID_OUT_DMI_CFG			0xa208
#define VFE_PP_CLC_DSX_C_VID_OUT_DMI_LUT_CFG			0xa20c
#define VFE_PP_CLC_DSX_C_VID_OUT_DMI_DATA			0xa210
#define VFE_PP_CLC_DSX_C_VID_OUT_DMI_CMD			0xa250
#define VFE_PP_CLC_DSX_C_VID_OUT_DMI_STATUS			0xa254
#define VFE_PP_CLC_DSX_C_VID_OUT_DMI_LUT_BANK_CFG		0xa258
#define VFE_PP_CLC_DSX_C_VID_OUT_MODULE_LUT_BANK_CFG		0xa25c
#define VFE_PP_CLC_DSX_C_VID_OUT_MODULE_CFG			0xa260
#define VFE_PP_CLC_DSX_C_VID_OUT_MODE				0xa264
#define VFE_PP_CLC_DSX_C_VID_OUT_START_LOCATION_X		0xa268
#define VFE_PP_CLC_DSX_C_VID_OUT_START_LOCATION_Y		0xa26c
#define VFE_PP_CLC_DSX_C_VID_OUT_SCALE_RATIO_X			0xa270
#define VFE_PP_CLC_DSX_C_VID_OUT_SCALE_RATIO_Y			0xa274
#define VFE_PP_CLC_DSX_C_VID_OUT_OUT_SIZE			0xa278
#define VFE_PP_CLC_DSX_C_VID_OUT_IN_SIZE			0xa27c
#define VFE_PP_CLC_DSX_C_VID_OUT_PADDING_WEIGHTS_TOP_BOT_CHROMA_0	0xa280
#define VFE_PP_CLC_DSX_C_VID_OUT_PADDING_WEIGHTS_TOP_BOT_CHROMA_1	0xa284
#define VFE_PP_CLC_DSX_C_VID_OUT_PADDING_WEIGHTS_TOP_BOT_CHROMA_2	0xa288
#define VFE_PP_CLC_DSX_C_VID_OUT_PADDING_WEIGHTS_TOP_BOT_CHROMA_3	0xa28c
#define VFE_PP_CLC_DSX_C_VID_OUT_PADDING_WEIGHTS_TOP_BOT_CHROMA_4	0xa290
#define VFE_PP_CLC_DSX_C_VID_OUT_PADDING_WEIGHTS_TOP_BOT_CHROMA_5	0xa294
#define VFE_PP_CLC_DSX_C_VID_OUT_PADDING_WEIGHTS_TOP_BOT_CHROMA_6	0xa298
#define VFE_PP_CLC_DSX_C_VID_OUT_PADDING_WEIGHTS_TOP_BOT_CHROMA_7	0xa2c0
#define VFE_PP_CLC_DSX_C_VID_OUT_PADDING_WEIGHTS_LEFT_RGT_CHROMA_0	0xa2c4
#define VFE_PP_CLC_DSX_C_VID_OUT_PADDING_WEIGHTS_LEFT_RGT_CHROMA_1	0xa2c8
#define VFE_PP_CLC_DSX_C_VID_OUT_PADDING_WEIGHTS_LEFT_RGT_CHROMA_2	0xa2cc
#define VFE_PP_CLC_DSX_C_VID_OUT_PADDING_WEIGHTS_LEFT_RGT_CHROMA_3	0xa2d0
#define VFE_PP_CLC_DSX_C_VID_OUT_PADDING_WEIGHTS_LEFT_RGT_CHROMA_4	0xa2d4
#define VFE_PP_CLC_DSX_C_VID_OUT_PADDING_WEIGHTS_LEFT_RGT_CHROMA_5	0xa2d8
#define VFE_PP_CLC_DSX_C_VID_OUT_PADDING_WEIGHTS_LEFT_RGT_CHROMA_6	0xa2dc
#define VFE_PP_CLC_DSX_C_VID_OUT_PADDING_WEIGHTS_LEFT_RGT_CHROMA_7	0xa2e0
#define VFE_PP_CLC_DSX_C_VID_OUT_TEST_BUS_CTRL			0xa3f8
#define VFE_PP_CLC_DSX_C_VID_OUT_SPARE				0xa3fc
/* DSX_C_VID_OUT: 15 LUT/DMI entries at 0xa214..0xa24c, index with a stride of 4 */

/* CROP_RND_CLAMP_POST_DSX_Y_VID_OUT  (base 0x6b00, absolute 0xa400) */
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DSX_Y_VID_OUT_HW_VERSION	0xa400
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DSX_Y_VID_OUT_HW_STATUS	0xa404
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DSX_Y_VID_OUT_MODULE_CFG	0xa460
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DSX_Y_VID_OUT_CROP_LINE_CFG	0xa468
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DSX_Y_VID_OUT_CROP_PIXEL_CFG	0xa46c
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DSX_Y_VID_OUT_CH0_CLAMP_MIN	0xa470
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DSX_Y_VID_OUT_CH0_ROUNDING_CFG	0xa474
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DSX_Y_VID_OUT_CH1_CLAMP_MIN	0xa478
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DSX_Y_VID_OUT_CH1_ROUNDING_CFG	0xa47c
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DSX_Y_VID_OUT_CH2_CLAMP_MIN	0xa480
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DSX_Y_VID_OUT_CH2_ROUNDING_CFG	0xa484
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DSX_Y_VID_OUT_CH0_CLAMP_MAX	0xa488
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DSX_Y_VID_OUT_CH1_CLAMP_MAX	0xa48c
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DSX_Y_VID_OUT_CH2_CLAMP_MAX	0xa490
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DSX_Y_VID_OUT_UNSIGNED_TO_SIGNED_BPP	0xa494
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DSX_Y_VID_OUT_TEST_BUS_CTRL	0xa5f8
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DSX_Y_VID_OUT_SPARE	0xa5fc

/* CROP_RND_CLAMP_POST_DSX_C_VID_OUT  (base 0x6d00, absolute 0xa600) */
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DSX_C_VID_OUT_HW_VERSION	0xa600
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DSX_C_VID_OUT_HW_STATUS	0xa604
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DSX_C_VID_OUT_MODULE_CFG	0xa660
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DSX_C_VID_OUT_CROP_LINE_CFG	0xa668
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DSX_C_VID_OUT_CROP_PIXEL_CFG	0xa66c
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DSX_C_VID_OUT_CH0_CLAMP_MIN	0xa670
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DSX_C_VID_OUT_CH0_ROUNDING_CFG	0xa674
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DSX_C_VID_OUT_CH1_CLAMP_MIN	0xa678
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DSX_C_VID_OUT_CH1_ROUNDING_CFG	0xa67c
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DSX_C_VID_OUT_CH2_CLAMP_MIN	0xa680
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DSX_C_VID_OUT_CH2_ROUNDING_CFG	0xa684
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DSX_C_VID_OUT_CH0_CLAMP_MAX	0xa688
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DSX_C_VID_OUT_CH1_CLAMP_MAX	0xa68c
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DSX_C_VID_OUT_CH2_CLAMP_MAX	0xa690
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DSX_C_VID_OUT_UNSIGNED_TO_SIGNED_BPP	0xa694
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DSX_C_VID_OUT_TEST_BUS_CTRL	0xa7f8
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DSX_C_VID_OUT_SPARE	0xa7fc

/* DOWNSCALE_4TO1_Y_VID_DS16_OUT  (base 0x6f00, absolute 0xa800) */
#define VFE_PP_CLC_DOWNSCALE_4TO1_Y_VID_DS16_OUT_HW_VERSION	0xa800
#define VFE_PP_CLC_DOWNSCALE_4TO1_Y_VID_DS16_OUT_HW_STATUS	0xa804
#define VFE_PP_CLC_DOWNSCALE_4TO1_Y_VID_DS16_OUT_MODULE_CFG	0xa860
#define VFE_PP_CLC_DOWNSCALE_4TO1_Y_VID_DS16_OUT_DS_COEFF	0xa868
#define VFE_PP_CLC_DOWNSCALE_4TO1_Y_VID_DS16_OUT_CROP_LINE_CFG	0xa904
#define VFE_PP_CLC_DOWNSCALE_4TO1_Y_VID_DS16_OUT_CROP_PIXEL_CFG	0xa908
#define VFE_PP_CLC_DOWNSCALE_4TO1_Y_VID_DS16_OUT_TEST_BUS_CTRL	0xa9f8
#define VFE_PP_CLC_DOWNSCALE_4TO1_Y_VID_DS16_OUT_SPARE		0xa9fc

/* DOWNSCALE_4TO1_C_VID_DS16_OUT  (base 0x7100, absolute 0xaa00) */
#define VFE_PP_CLC_DOWNSCALE_4TO1_C_VID_DS16_OUT_HW_VERSION	0xaa00
#define VFE_PP_CLC_DOWNSCALE_4TO1_C_VID_DS16_OUT_HW_STATUS	0xaa04
#define VFE_PP_CLC_DOWNSCALE_4TO1_C_VID_DS16_OUT_MODULE_CFG	0xaa60
#define VFE_PP_CLC_DOWNSCALE_4TO1_C_VID_DS16_OUT_CROP_LINE_CFG	0xab04
#define VFE_PP_CLC_DOWNSCALE_4TO1_C_VID_DS16_OUT_CROP_PIXEL_CFG	0xab08
#define VFE_PP_CLC_DOWNSCALE_4TO1_C_VID_DS16_OUT_TEST_BUS_CTRL	0xabf8
#define VFE_PP_CLC_DOWNSCALE_4TO1_C_VID_DS16_OUT_SPARE		0xabfc

/* CROP_RND_CLAMP_POST_DOWNSCALE_4TO1_Y_VID_DS16_OUT  (base 0x7300, absolute 0xac00) */
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_4TO1_Y_VID_DS16_OUT_HW_VERSION	0xac00
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_4TO1_Y_VID_DS16_OUT_HW_STATUS	0xac04
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_4TO1_Y_VID_DS16_OUT_MODULE_CFG	0xac60
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_4TO1_Y_VID_DS16_OUT_CROP_LINE_CFG	0xac68
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_4TO1_Y_VID_DS16_OUT_CROP_PIXEL_CFG	0xac6c
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_4TO1_Y_VID_DS16_OUT_CH0_CLAMP_MIN	0xac70
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_4TO1_Y_VID_DS16_OUT_CH0_ROUNDING_CFG	0xac74
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_4TO1_Y_VID_DS16_OUT_CH1_CLAMP_MIN	0xac78
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_4TO1_Y_VID_DS16_OUT_CH1_ROUNDING_CFG	0xac7c
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_4TO1_Y_VID_DS16_OUT_CH2_CLAMP_MIN	0xac80
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_4TO1_Y_VID_DS16_OUT_CH2_ROUNDING_CFG	0xac84
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_4TO1_Y_VID_DS16_OUT_CH0_CLAMP_MAX	0xac88
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_4TO1_Y_VID_DS16_OUT_CH1_CLAMP_MAX	0xac8c
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_4TO1_Y_VID_DS16_OUT_CH2_CLAMP_MAX	0xac90
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_4TO1_Y_VID_DS16_OUT_UNSIGNED_TO_SIGNED_BPP	0xac94
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_4TO1_Y_VID_DS16_OUT_TEST_BUS_CTRL	0xadf8
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_4TO1_Y_VID_DS16_OUT_SPARE	0xadfc

/* CROP_RND_CLAMP_POST_DOWNSCALE_4TO1_C_VID_DS16_OUT  (base 0x7500, absolute 0xae00) */
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_4TO1_C_VID_DS16_OUT_HW_VERSION	0xae00
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_4TO1_C_VID_DS16_OUT_HW_STATUS	0xae04
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_4TO1_C_VID_DS16_OUT_MODULE_CFG	0xae60
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_4TO1_C_VID_DS16_OUT_CROP_LINE_CFG	0xae68
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_4TO1_C_VID_DS16_OUT_CROP_PIXEL_CFG	0xae6c
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_4TO1_C_VID_DS16_OUT_CH0_CLAMP_MIN	0xae70
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_4TO1_C_VID_DS16_OUT_CH0_ROUNDING_CFG	0xae74
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_4TO1_C_VID_DS16_OUT_CH1_CLAMP_MIN	0xae78
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_4TO1_C_VID_DS16_OUT_CH1_ROUNDING_CFG	0xae7c
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_4TO1_C_VID_DS16_OUT_CH2_CLAMP_MIN	0xae80
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_4TO1_C_VID_DS16_OUT_CH2_ROUNDING_CFG	0xae84
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_4TO1_C_VID_DS16_OUT_CH0_CLAMP_MAX	0xae88
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_4TO1_C_VID_DS16_OUT_CH1_CLAMP_MAX	0xae8c
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_4TO1_C_VID_DS16_OUT_CH2_CLAMP_MAX	0xae90
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_4TO1_C_VID_DS16_OUT_UNSIGNED_TO_SIGNED_BPP	0xae94
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_4TO1_C_VID_DS16_OUT_TEST_BUS_CTRL	0xaff8
#define VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_4TO1_C_VID_DS16_OUT_SPARE	0xaffc

/* STATS_AEC_BE  (base 0x7700, absolute 0xb000) */
#define VFE_PP_CLC_STATS_AEC_BE_HW_VERSION			0xb000
#define VFE_PP_CLC_STATS_AEC_BE_HW_STATUS			0xb004
#define VFE_PP_CLC_STATS_AEC_BE_MODULE_CFG			0xb060
#define VFE_PP_CLC_STATS_AEC_BE_BLACK_LEVEL_SUB_CFG		0xb064
#define VFE_PP_CLC_STATS_AEC_BE_CH_Y_CFG			0xb068
#define VFE_PP_CLC_STATS_AEC_BE_HORZ_RGN_CFG_0			0xb06c
#define VFE_PP_CLC_STATS_AEC_BE_HORZ_RGN_CFG_1			0xb070
#define VFE_PP_CLC_STATS_AEC_BE_VERT_RGN_CFG_0			0xb074
#define VFE_PP_CLC_STATS_AEC_BE_VERT_RGN_CFG_1			0xb078
#define VFE_PP_CLC_STATS_AEC_BE_RGN_WIDTH_CFG			0xb07c
#define VFE_PP_CLC_STATS_AEC_BE_HI_THRESHOLD_CFG_0		0xb080
#define VFE_PP_CLC_STATS_AEC_BE_HI_THRESHOLD_CFG_1		0xb084
#define VFE_PP_CLC_STATS_AEC_BE_HI_THRESHOLD_CFG_2		0xb088
#define VFE_PP_CLC_STATS_AEC_BE_HI_THRESHOLD_CFG_3		0xb08c
#define VFE_PP_CLC_STATS_AEC_BE_HI_THRESHOLD_CFG_4		0xb090
#define VFE_PP_CLC_STATS_AEC_BE_LO_THRESHOLD_CFG_0		0xb094
#define VFE_PP_CLC_STATS_AEC_BE_LO_THRESHOLD_CFG_1		0xb098
#define VFE_PP_CLC_STATS_AEC_BE_LO_THRESHOLD_CFG_2		0xb09c
#define VFE_PP_CLC_STATS_AEC_BE_LO_THRESHOLD_CFG_3		0xb0a0
#define VFE_PP_CLC_STATS_AEC_BE_LO_THRESHOLD_CFG_4		0xb0a4
#define VFE_PP_CLC_STATS_AEC_BE_TEST_BUS_CTRL			0xb1f8
#define VFE_PP_CLC_STATS_AEC_BE_SPARE				0xb1fc

/* STATS_AEC_BHIST  (base 0x7900, absolute 0xb200) */
#define VFE_PP_CLC_STATS_AEC_BHIST_HW_VERSION			0xb200
#define VFE_PP_CLC_STATS_AEC_BHIST_HW_STATUS			0xb204
#define VFE_PP_CLC_STATS_AEC_BHIST_DMI_CFG			0xb208
#define VFE_PP_CLC_STATS_AEC_BHIST_DMI_LUT_CFG			0xb20c
#define VFE_PP_CLC_STATS_AEC_BHIST_DMI_DATA			0xb210
#define VFE_PP_CLC_STATS_AEC_BHIST_DMI_CMD			0xb250
#define VFE_PP_CLC_STATS_AEC_BHIST_DMI_STATUS			0xb254
#define VFE_PP_CLC_STATS_AEC_BHIST_DMI_LUT_BANK_CFG		0xb258
#define VFE_PP_CLC_STATS_AEC_BHIST_MODULE_LUT_BANK_CFG		0xb25c
#define VFE_PP_CLC_STATS_AEC_BHIST_MODULE_CFG			0xb260
#define VFE_PP_CLC_STATS_AEC_BHIST_BLACK_LEVEL_SUB_CFG_0	0xb264
#define VFE_PP_CLC_STATS_AEC_BHIST_RGN_OFFSET_CFG		0xb268
#define VFE_PP_CLC_STATS_AEC_BHIST_RGN_NUM_CFG			0xb26c
#define VFE_PP_CLC_STATS_AEC_BHIST_SEGMENT_BASE_CFG_0		0xb270
#define VFE_PP_CLC_STATS_AEC_BHIST_SEGMENT_BASE_CFG_1		0xb274
#define VFE_PP_CLC_STATS_AEC_BHIST_SEGMENT_BASE_CFG_2		0xb278
#define VFE_PP_CLC_STATS_AEC_BHIST_SEGMENT_BASE_CFG_3		0xb27c
#define VFE_PP_CLC_STATS_AEC_BHIST_SEGMENT_BASE_CFG_4		0xb280
#define VFE_PP_CLC_STATS_AEC_BHIST_SEGMENT_BASE_CFG_5		0xb284
#define VFE_PP_CLC_STATS_AEC_BHIST_SEGMENT_BASE_CFG_6		0xb288
#define VFE_PP_CLC_STATS_AEC_BHIST_SEGMENT_BASE_CFG_7		0xb28c
#define VFE_PP_CLC_STATS_AEC_BHIST_SEGMENT_SLOPE_CFG_0		0xb290
#define VFE_PP_CLC_STATS_AEC_BHIST_SEGMENT_SLOPE_CFG_1		0xb294
#define VFE_PP_CLC_STATS_AEC_BHIST_SEGMENT_START_BIN_CFG_0	0xb298
#define VFE_PP_CLC_STATS_AEC_BHIST_SEGMENT_START_BIN_CFG_1	0xb29c
#define VFE_PP_CLC_STATS_AEC_BHIST_SEGMENT_START_BIN_CFG_2	0xb2a0
#define VFE_PP_CLC_STATS_AEC_BHIST_Y_CONV_COEFF_CFG		0xb2a4
#define VFE_PP_CLC_STATS_AEC_BHIST_DEBUG_STATUS			0xb2a8
#define VFE_PP_CLC_STATS_AEC_BHIST_TEST_BUS_CTRL		0xb3f8
#define VFE_PP_CLC_STATS_AEC_BHIST_SPARE			0xb3fc
/* STATS_AEC_BHIST: 15 LUT/DMI entries at 0xb214..0xb24c, index with a stride of 4 */

/* STATS_BHIST  (base 0x7b00, absolute 0xb400) */
#define VFE_PP_CLC_STATS_BHIST_HW_VERSION			0xb400
#define VFE_PP_CLC_STATS_BHIST_HW_STATUS			0xb404
#define VFE_PP_CLC_STATS_BHIST_DMI_CFG				0xb408
#define VFE_PP_CLC_STATS_BHIST_DMI_LUT_CFG			0xb40c
#define VFE_PP_CLC_STATS_BHIST_DMI_DATA				0xb410
#define VFE_PP_CLC_STATS_BHIST_DMI_CMD				0xb450
#define VFE_PP_CLC_STATS_BHIST_DMI_STATUS			0xb454
#define VFE_PP_CLC_STATS_BHIST_DMI_LUT_BANK_CFG			0xb458
#define VFE_PP_CLC_STATS_BHIST_MODULE_LUT_BANK_CFG		0xb45c
#define VFE_PP_CLC_STATS_BHIST_MODULE_CFG			0xb460
#define VFE_PP_CLC_STATS_BHIST_BLACK_LEVEL_SUB_CFG_0		0xb464
#define VFE_PP_CLC_STATS_BHIST_RGN_OFFSET_CFG			0xb468
#define VFE_PP_CLC_STATS_BHIST_RGN_NUM_CFG			0xb46c
#define VFE_PP_CLC_STATS_BHIST_SEGMENT_BASE_CFG_0		0xb470
#define VFE_PP_CLC_STATS_BHIST_SEGMENT_BASE_CFG_1		0xb474
#define VFE_PP_CLC_STATS_BHIST_SEGMENT_BASE_CFG_2		0xb478
#define VFE_PP_CLC_STATS_BHIST_SEGMENT_BASE_CFG_3		0xb47c
#define VFE_PP_CLC_STATS_BHIST_SEGMENT_BASE_CFG_4		0xb480
#define VFE_PP_CLC_STATS_BHIST_SEGMENT_BASE_CFG_5		0xb484
#define VFE_PP_CLC_STATS_BHIST_SEGMENT_BASE_CFG_6		0xb488
#define VFE_PP_CLC_STATS_BHIST_SEGMENT_BASE_CFG_7		0xb48c
#define VFE_PP_CLC_STATS_BHIST_SEGMENT_SLOPE_CFG_0		0xb490
#define VFE_PP_CLC_STATS_BHIST_SEGMENT_SLOPE_CFG_1		0xb494
#define VFE_PP_CLC_STATS_BHIST_SEGMENT_START_BIN_CFG_0		0xb498
#define VFE_PP_CLC_STATS_BHIST_SEGMENT_START_BIN_CFG_1		0xb49c
#define VFE_PP_CLC_STATS_BHIST_SEGMENT_START_BIN_CFG_2		0xb4a0
#define VFE_PP_CLC_STATS_BHIST_Y_CONV_COEFF_CFG			0xb4a4
#define VFE_PP_CLC_STATS_BHIST_DEBUG_STATUS			0xb4a8
#define VFE_PP_CLC_STATS_BHIST_TEST_BUS_CTRL			0xb5f8
#define VFE_PP_CLC_STATS_BHIST_SPARE				0xb5fc
/* STATS_BHIST: 15 LUT/DMI entries at 0xb414..0xb44c, index with a stride of 4 */

/* STATS_TINTLESS_BG  (base 0x7d00, absolute 0xb600) */
#define VFE_PP_CLC_STATS_TINTLESS_BG_HW_VERSION			0xb600
#define VFE_PP_CLC_STATS_TINTLESS_BG_HW_STATUS			0xb604
#define VFE_PP_CLC_STATS_TINTLESS_BG_MODULE_CFG			0xb660
#define VFE_PP_CLC_STATS_TINTLESS_BG_BLACK_LEVEL_SUB_CFG	0xb664
#define VFE_PP_CLC_STATS_TINTLESS_BG_CH_Y_CFG			0xb668
#define VFE_PP_CLC_STATS_TINTLESS_BG_HORZ_RGN_CFG_0		0xb66c
#define VFE_PP_CLC_STATS_TINTLESS_BG_HORZ_RGN_CFG_1		0xb670
#define VFE_PP_CLC_STATS_TINTLESS_BG_VERT_RGN_CFG_0		0xb674
#define VFE_PP_CLC_STATS_TINTLESS_BG_VERT_RGN_CFG_1		0xb678
#define VFE_PP_CLC_STATS_TINTLESS_BG_RGN_WIDTH_CFG		0xb67c
#define VFE_PP_CLC_STATS_TINTLESS_BG_HI_THRESHOLD_CFG_0		0xb680
#define VFE_PP_CLC_STATS_TINTLESS_BG_HI_THRESHOLD_CFG_1		0xb684
#define VFE_PP_CLC_STATS_TINTLESS_BG_HI_THRESHOLD_CFG_2		0xb688
#define VFE_PP_CLC_STATS_TINTLESS_BG_HI_THRESHOLD_CFG_3		0xb68c
#define VFE_PP_CLC_STATS_TINTLESS_BG_HI_THRESHOLD_CFG_4		0xb690
#define VFE_PP_CLC_STATS_TINTLESS_BG_LO_THRESHOLD_CFG_0		0xb694
#define VFE_PP_CLC_STATS_TINTLESS_BG_LO_THRESHOLD_CFG_1		0xb698
#define VFE_PP_CLC_STATS_TINTLESS_BG_LO_THRESHOLD_CFG_2		0xb69c
#define VFE_PP_CLC_STATS_TINTLESS_BG_LO_THRESHOLD_CFG_3		0xb6a0
#define VFE_PP_CLC_STATS_TINTLESS_BG_LO_THRESHOLD_CFG_4		0xb6a4
#define VFE_PP_CLC_STATS_TINTLESS_BG_TEST_BUS_CTRL		0xb7f8
#define VFE_PP_CLC_STATS_TINTLESS_BG_SPARE			0xb7fc

/* STATS_AWB_BG  (base 0x7f00, absolute 0xb800) */
#define VFE_PP_CLC_STATS_AWB_BG_HW_VERSION			0xb800
#define VFE_PP_CLC_STATS_AWB_BG_HW_STATUS			0xb804
#define VFE_PP_CLC_STATS_AWB_BG_MODULE_CFG			0xb860
#define VFE_PP_CLC_STATS_AWB_BG_BLACK_LEVEL_SUB_CFG		0xb864
#define VFE_PP_CLC_STATS_AWB_BG_CH_Y_CFG			0xb868
#define VFE_PP_CLC_STATS_AWB_BG_HORZ_RGN_CFG_0			0xb86c
#define VFE_PP_CLC_STATS_AWB_BG_HORZ_RGN_CFG_1			0xb870
#define VFE_PP_CLC_STATS_AWB_BG_VERT_RGN_CFG_0			0xb874
#define VFE_PP_CLC_STATS_AWB_BG_VERT_RGN_CFG_1			0xb878
#define VFE_PP_CLC_STATS_AWB_BG_RGN_WIDTH_CFG			0xb87c
#define VFE_PP_CLC_STATS_AWB_BG_HI_THRESHOLD_CFG_0		0xb880
#define VFE_PP_CLC_STATS_AWB_BG_HI_THRESHOLD_CFG_1		0xb884
#define VFE_PP_CLC_STATS_AWB_BG_HI_THRESHOLD_CFG_2		0xb888
#define VFE_PP_CLC_STATS_AWB_BG_HI_THRESHOLD_CFG_3		0xb88c
#define VFE_PP_CLC_STATS_AWB_BG_HI_THRESHOLD_CFG_4		0xb890
#define VFE_PP_CLC_STATS_AWB_BG_LO_THRESHOLD_CFG_0		0xb894
#define VFE_PP_CLC_STATS_AWB_BG_LO_THRESHOLD_CFG_1		0xb898
#define VFE_PP_CLC_STATS_AWB_BG_LO_THRESHOLD_CFG_2		0xb89c
#define VFE_PP_CLC_STATS_AWB_BG_LO_THRESHOLD_CFG_3		0xb8a0
#define VFE_PP_CLC_STATS_AWB_BG_LO_THRESHOLD_CFG_4		0xb8a4
#define VFE_PP_CLC_STATS_AWB_BG_TEST_BUS_CTRL			0xb9f8
#define VFE_PP_CLC_STATS_AWB_BG_SPARE				0xb9fc

/* STATS_BFW  (base 0x8100, absolute 0xba00) */
#define VFE_PP_CLC_STATS_BFW_HW_VERSION				0xba00
#define VFE_PP_CLC_STATS_BFW_HW_STATUS				0xba04
#define VFE_PP_CLC_STATS_BFW_DMI_CFG				0xba08
#define VFE_PP_CLC_STATS_BFW_DMI_LUT_CFG			0xba0c
#define VFE_PP_CLC_STATS_BFW_DMI_DATA				0xba10
#define VFE_PP_CLC_STATS_BFW_DMI_CMD				0xba50
#define VFE_PP_CLC_STATS_BFW_DMI_STATUS				0xba54
#define VFE_PP_CLC_STATS_BFW_DMI_LUT_BANK_CFG			0xba58
#define VFE_PP_CLC_STATS_BFW_MODULE_LUT_BANK_CFG		0xba5c
#define VFE_PP_CLC_STATS_BFW_MODULE_CFG				0xba60
#define VFE_PP_CLC_STATS_BFW_BLACK_LEVEL_SUB_CFG		0xba64
#define VFE_PP_CLC_STATS_BFW_CH_Y_CFG				0xba68
#define VFE_PP_CLC_STATS_BFW_HI_THRESHOLD_CFG_0			0xba80
#define VFE_PP_CLC_STATS_BFW_HI_THRESHOLD_CFG_1			0xba84
#define VFE_PP_CLC_STATS_BFW_HI_THRESHOLD_CFG_2			0xba88
#define VFE_PP_CLC_STATS_BFW_HI_THRESHOLD_CFG_3			0xba8c
#define VFE_PP_CLC_STATS_BFW_HI_THRESHOLD_CFG_4			0xba90
#define VFE_PP_CLC_STATS_BFW_LO_THRESHOLD_CFG_0			0xba94
#define VFE_PP_CLC_STATS_BFW_LO_THRESHOLD_CFG_1			0xba98
#define VFE_PP_CLC_STATS_BFW_LO_THRESHOLD_CFG_2			0xba9c
#define VFE_PP_CLC_STATS_BFW_LO_THRESHOLD_CFG_3			0xbaa0
#define VFE_PP_CLC_STATS_BFW_LO_THRESHOLD_CFG_4			0xbaa4
#define VFE_PP_CLC_STATS_BFW_TEST_BUS_CTRL			0xbbf8
#define VFE_PP_CLC_STATS_BFW_SPARE				0xbbfc
/* STATS_BFW: 15 LUT/DMI entries at 0xba14..0xba4c, index with a stride of 4 */

/* STATS_BAF  (base 0x8300, absolute 0xbc00) */
#define VFE_PP_CLC_STATS_BAF_HW_VERSION				0xbc00
#define VFE_PP_CLC_STATS_BAF_HW_STATUS				0xbc04
#define VFE_PP_CLC_STATS_BAF_DMI_CFG				0xbc08
#define VFE_PP_CLC_STATS_BAF_DMI_LUT_CFG			0xbc0c
#define VFE_PP_CLC_STATS_BAF_DMI_DATA				0xbc10
#define VFE_PP_CLC_STATS_BAF_DMI_CMD				0xbc50
#define VFE_PP_CLC_STATS_BAF_DMI_STATUS				0xbc54
#define VFE_PP_CLC_STATS_BAF_DMI_LUT_BANK_CFG			0xbc58
#define VFE_PP_CLC_STATS_BAF_MODULE_LUT_BANK_CFG		0xbc5c
#define VFE_PP_CLC_STATS_BAF_MODULE_CFG				0xbc60
#define VFE_PP_CLC_STATS_BAF_Y_CONV_CFG_0			0xbc64
#define VFE_PP_CLC_STATS_BAF_Y_CONV_CFG_1			0xbc68
#define VFE_PP_CLC_STATS_BAF_H_1_FIR_CFG_0			0xbc6c
#define VFE_PP_CLC_STATS_BAF_H_1_FIR_CFG_1			0xbc70
#define VFE_PP_CLC_STATS_BAF_H_1_FIR_CFG_2			0xbc74
#define VFE_PP_CLC_STATS_BAF_H_1_FIR_CFG_3			0xbc78
#define VFE_PP_CLC_STATS_BAF_H_1_IIR_CFG_0			0xbc7c
#define VFE_PP_CLC_STATS_BAF_H_1_IIR_CFG_1			0xbc80
#define VFE_PP_CLC_STATS_BAF_H_1_IIR_CFG_2			0xbc84
#define VFE_PP_CLC_STATS_BAF_H_1_IIR_CFG_3			0xbc88
#define VFE_PP_CLC_STATS_BAF_H_1_IIR_CFG_4			0xbc8c
#define VFE_PP_CLC_STATS_BAF_V_IIR_CFG_0			0xbc90
#define VFE_PP_CLC_STATS_BAF_V_IIR_CFG_1			0xbc94
#define VFE_PP_CLC_STATS_BAF_V_IIR_CFG_2			0xbc98
#define VFE_PP_CLC_STATS_BAF_V_IIR_CFG_3			0xbc9c
#define VFE_PP_CLC_STATS_BAF_V_IIR_CFG_4			0xbca0
#define VFE_PP_CLC_STATS_BAF_V_IIR_CFG_5			0xbca4
#define VFE_PP_CLC_STATS_BAF_SHIFT_BITS_CFG			0xbca8
#define VFE_PP_CLC_STATS_BAF_H_1_TH_CFG				0xbcac
#define VFE_PP_CLC_STATS_BAF_H_1_CORING_CFG_0			0xbcb0
#define VFE_PP_CLC_STATS_BAF_H_1_CORING_CFG_1			0xbcb4
#define VFE_PP_CLC_STATS_BAF_H_1_CORING_CFG_2			0xbcb8
#define VFE_PP_CLC_STATS_BAF_H_1_CORING_CFG_3			0xbcbc
#define VFE_PP_CLC_STATS_BAF_V_TH_CFG				0xbcc0
#define VFE_PP_CLC_STATS_BAF_V_CORING_CFG_0			0xbcc4
#define VFE_PP_CLC_STATS_BAF_V_CORING_CFG_1			0xbcc8
#define VFE_PP_CLC_STATS_BAF_V_CORING_CFG_2			0xbccc
#define VFE_PP_CLC_STATS_BAF_V_CORING_CFG_3			0xbcd0
#define VFE_PP_CLC_STATS_BAF_CORING_GAIN_CFG_0			0xbcd4
#define VFE_PP_CLC_STATS_BAF_CORING_GAIN_CFG_1			0xbcd8
#define VFE_PP_CLC_STATS_BAF_SCALE_H_IMAGE_SIZE_CFG		0xbcdc
#define VFE_PP_CLC_STATS_BAF_SCALE_H_PHASE_CFG			0xbce0
#define VFE_PP_CLC_STATS_BAF_SCALE_H_STRIPE_CFG_0		0xbce4
#define VFE_PP_CLC_STATS_BAF_SCALE_H_STRIPE_CFG_1		0xbce8
#define VFE_PP_CLC_STATS_BAF_SCALE_H_PAD_CFG			0xbcec
#define VFE_PP_CLC_STATS_BAF_ROI_XY_MIN				0xbcf0
#define VFE_PP_CLC_STATS_BAF_ROI_XY_MAX				0xbcf4
#define VFE_PP_CLC_STATS_BAF_DEBUG_STATUS			0xbdf4
#define VFE_PP_CLC_STATS_BAF_TEST_BUS_CTRL			0xbdf8
#define VFE_PP_CLC_STATS_BAF_SPARE				0xbdfc
/* STATS_BAF: 15 LUT/DMI entries at 0xbc14..0xbc4c, index with a stride of 4 */

/* STATS_RS  (base 0x8500, absolute 0xbe00) */
#define VFE_PP_CLC_STATS_RS_HW_VERSION				0xbe00
#define VFE_PP_CLC_STATS_RS_HW_STATUS				0xbe04
#define VFE_PP_CLC_STATS_RS_MODULE_CFG				0xbe60
#define VFE_PP_CLC_STATS_RS_RGN_OFFSET_CFG			0xbe68
#define VFE_PP_CLC_STATS_RS_RGN_NUM_CFG				0xbe6c
#define VFE_PP_CLC_STATS_RS_RGN_SIZE_CFG			0xbe70
#define VFE_PP_CLC_STATS_RS_DEBUG_STATUS			0xbe74
#define VFE_PP_CLC_STATS_RS_TEST_BUS_CTRL			0xbff8
#define VFE_PP_CLC_STATS_RS_SPARE				0xbffc

/* STATS_IHIST  (base 0x8700, absolute 0xc000) */
#define VFE_PP_CLC_STATS_IHIST_HW_VERSION			0xc000
#define VFE_PP_CLC_STATS_IHIST_HW_STATUS			0xc004
#define VFE_PP_CLC_STATS_IHIST_DMI_CFG				0xc008
#define VFE_PP_CLC_STATS_IHIST_DMI_LUT_CFG			0xc00c
#define VFE_PP_CLC_STATS_IHIST_DMI_DATA				0xc010
#define VFE_PP_CLC_STATS_IHIST_DMI_CMD				0xc050
#define VFE_PP_CLC_STATS_IHIST_DMI_STATUS			0xc054
#define VFE_PP_CLC_STATS_IHIST_DMI_LUT_BANK_CFG			0xc058
#define VFE_PP_CLC_STATS_IHIST_MODULE_LUT_BANK_CFG		0xc05c
#define VFE_PP_CLC_STATS_IHIST_MODULE_CFG			0xc060
#define VFE_PP_CLC_STATS_IHIST_RGN_OFFSET_CFG			0xc068
#define VFE_PP_CLC_STATS_IHIST_RGN_NUM_CFG			0xc06c
#define VFE_PP_CLC_STATS_IHIST_DEBUG_STATUS			0xc070
#define VFE_PP_CLC_STATS_IHIST_TEST_BUS_CTRL			0xc1f8
#define VFE_PP_CLC_STATS_IHIST_SPARE				0xc1fc
/* STATS_IHIST: 15 LUT/DMI entries at 0xc014..0xc04c, index with a stride of 4 */

/*
 * Shorthand for the outputs the driver programs directly. The generated
 * names above follow the hardware naming and are unwieldy at a call site.
 */
#define VFE_PP_PIX_RAW_CFG		VFE_PP_CLC_CROP_RND_CLAMP_PIXEL_RAW_OUT_MODULE_CFG
#define VFE_PP_PIX_RAW_LINE		VFE_PP_CLC_CROP_RND_CLAMP_PIXEL_RAW_OUT_CROP_LINE_CFG
#define VFE_PP_PIX_RAW_PIXEL		VFE_PP_CLC_CROP_RND_CLAMP_PIXEL_RAW_OUT_CROP_PIXEL_CFG

#define VFE_PP_VID_Y_CFG		VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_MN_Y_VID_OUT_MODULE_CFG
#define VFE_PP_VID_Y_LINE		VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_MN_Y_VID_OUT_CROP_LINE_CFG
#define VFE_PP_VID_Y_PIXEL		VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_MN_Y_VID_OUT_CROP_PIXEL_CFG

#define VFE_PP_VID_C_CFG		VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_MN_C_VID_OUT_MODULE_CFG
#define VFE_PP_VID_C_LINE		VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_MN_C_VID_OUT_CROP_LINE_CFG
#define VFE_PP_VID_C_PIXEL		VFE_PP_CLC_CROP_RND_CLAMP_POST_DOWNSCALE_MN_C_VID_OUT_CROP_PIXEL_CFG

/*
 * CROP_LINE_CFG and CROP_PIXEL_CFG hold (last << 16) | first. For a full
 * frame only the last line and pixel are significant.
 */
#define VFE_PP_CROP_FIRST_SHIFT		0
#define VFE_PP_CROP_LAST_SHIFT		16

/* Values observed in the vendor driver for the video luma and chroma crop */
#define VFE_PP_VID_Y_CFG_VAL		0x0e01
#define VFE_PP_VID_C_CFG_VAL		0x3e01

/* DEMOSAIC MODULE_CFG: enable plus cosited chroma siting */
#define VFE_PP_DEMOSAIC_COSITED		BIT(14)

#endif /* __CAMSS_VFE_680_PP_REGS_H__ */
